import type { FindingKind, OriginKind, ResourceType, SegmentKind, WorkHourKind } from './types/calendar'

/**
 * Every UI text in one place (German). Help texts live in
 * `help/helpContent.ts`. Pure functions in `utils/` take their labels from
 * here too, so the wording stays consistent between calendar, inspector
 * and diagnostics.
 */

const plural = (n: number, one: string, many: string) => `${n.toLocaleString('de-DE')} ${n === 1 ? one : many}`
const hours = (h: number) => `${h.toLocaleString('de-DE', { maximumFractionDigits: 2 })} h`

export const S = {
  app: {
    title: 'Arbeitszeiten & Kalender',
    nav: { resources: 'Ressourcen', templates: 'Vorlagen', holidays: 'Feiertage', diagnostics: 'Diagnose', runs: 'Läufe', setup: 'Einrichtung' },
    navLabel: 'Bereiche',
    help: 'Hilfe',
    helpTitle: 'Hilfe zum aktuellen Bereich',
    modeMock: 'Mock-Daten',
    modeDataverse: 'Dataverse',
    modeMockTitle: 'Kein Power-Apps-Host — fiktive Beispieldaten im Speicher',
    loading: 'Lade …',
    readOnly: 'Nur lesen',
    readOnlyTitle: 'Speichern wurde wegen fehlender Berechtigung abgelehnt — die App zeigt nur noch an.',
    loadError: (what: string, err: string) => `${what} konnten nicht geladen werden: ${err}`,
    slotsUnavailable: (err: string) => `msdyn_LoadCalendars nicht erreichbar (${err}) — Arbeitszeit wird aus den Regeln abgeleitet, nicht aus den aufgelösten Slots.`,
    reload: 'Neu laden',
  },

  toolbar: {
    week: 'Woche',
    month: 'Monat',
    today: 'Heute',
    prev: 'Zurück',
    next: 'Weiter',
    viewerZone: 'Anzeige-Zeitzone',
    useV2: 'UseV2',
    useV2Title: 'Mehrere Wiederholungen parallel (V2-Überlappungslogik) bei jedem Speichern mitsenden',
    viewMode: 'Ansicht',
  },

  resources: {
    tabs: { list: 'Liste', calendar: 'Kalender' },
    search: 'Ressource suchen …',
    unit: 'Org-Einheit',
    category: 'Kategorie',
    territory: 'Gebiet',
    showInactive: 'Inaktive zeigen',
    onlyFindings: 'Nur mit Befunden',
    columns: { name: 'Name', type: 'Typ', unit: 'Org-Einheit', categories: 'Kategorien', zone: 'Zeitzone', status: 'Status', findings: 'Befunde', week: 'Stunden', rules: 'Regeln' },
    active: 'Aktiv',
    inactive: 'Inaktiv',
    noCalendar: 'kein Kalender',
    rulesCount: (n: number) => plural(n, 'Regel', 'Regeln'),
    selected: (n: number) => `${plural(n, 'Ressource', 'Ressourcen')} gewählt`,
    clearSelection: 'Auswahl aufheben',
    empty: 'Keine Ressourcen gefunden.',
    emptyEnv: 'Keine Ressourcen sichtbar. Hat die Umgebung Field Service / URS, und hat das Konto Leserecht auf „Buchbare Ressource“?',
    showDetails: 'Details anzeigen',
    selectAll: 'Alle wählen',
    selectRow: 'Wählen',
    openForm: 'In Dynamics öffnen',
    hoursInRange: hours,
    capacity: (h: number) => `Kapazität ${hours(h)}`,
  },

  calendar: {
    week: 'Wochenansicht',
    month: 'Monatsansicht',
    pickResource: 'Für die Monatsansicht eine Ressource in der Liste anklicken (Details).',
    noResources: 'Keine Ressource im Filter.',
    hours: hours,
    noWork: 'keine Arbeitszeit',
    total: 'Summe',
    legend: 'Legende',
    origin: 'Herkunft',
    rule: 'Regel',
    showRule: 'Regel im Inspektor zeigen',
    editDay: 'Diesen Tag ändern',
    addAbsence: 'Abwesenheit an diesem Tag',
    addWork: 'Arbeitszeit an diesem Tag',
    derived: 'aus Regeln abgeleitet',
    fromSlots: 'aus msdyn_LoadCalendars',
    closedDay: 'Schließung',
    slotCount: (n: number) => plural(n, 'Slot', 'Slots'),
    dayTitle: (date: string, h: string) => `${date} · ${h}`,
    effort: (e: number) => `Kapazität ${e}`,
    outsideMonth: 'anderer Monat',
    todayMark: 'Heute',
  },

  kinds: {
    work: 'Arbeitszeit',
    break: 'Pause',
    nonwork: 'Nicht-Arbeit',
    timeoff: 'Abwesenheit',
    closure: 'Geschäftsschließung',
    unknown: 'Unbekannt',
  } satisfies Record<WorkHourKind, string>,

  segments: {
    work: 'Arbeitszeit',
    break: 'Pause',
    timeoff: 'Abwesenheit',
    nonwork: 'Nicht-Arbeit',
    closure: 'Schließung',
  } satisfies Record<SegmentKind, string>,

  origins: {
    recurrence: 'Wiederholung',
    occurrence: 'Einzeltag',
    break: 'Pause',
    timeoff: 'Abwesenheit',
    nonwork: 'Nicht-Arbeit',
    closure: 'Schließung',
    slot: 'Arbeitszeit (Regel unbekannt)',
  } satisfies Record<OriginKind, string>,

  reasons: {
    none: '',
    timeoff: 'Abwesenheit',
    closure: 'Geschäftsschließung',
    nonwork: 'Nicht-Arbeit',
    noRule: 'Keine Arbeitszeitregel',
    ruleEnded: 'Regel ausgelaufen',
    ruleNotStarted: 'Regel beginnt später',
    weekdayOff: 'Kein Arbeitstag',
  },

  resourceTypes: {
    generic: 'Generisch',
    contact: 'Kontakt',
    user: 'Benutzer',
    equipment: 'Ausrüstung',
    account: 'Firma',
    crew: 'Team',
    facility: 'Einrichtung',
    pool: 'Pool',
  } satisfies Record<ResourceType, string>,

  rules: {
    weekly: 'Wöchentlich',
    daily: 'Täglich',
    once: 'Einmal',
    allDay: 'ganztägig',
    varied: 'je Wochentag verschieden',
    openEnd: 'ohne Ende',
    from: 'ab',
    until: 'bis',
    capacity: 'Kapazität',
    rank0: 'Rang 0 — wöchentliche Wiederholung',
    rank1: 'Rang 1 — Einzeltag/Abwesenheit, schlägt Rang 0',
    root: 'Wurzelregel',
    inner: 'Innerer Kalender',
    leaf: 'Blattregel',
    orphan: 'Verwaister innerer Kalender',
    unparsed: 'Nicht interpretierbare Regel',
    ends: (date: string) => `endet ${date}`,
    ended: (date: string) => `endete ${date}`,
    pauseAt: (range: string) => `Pause ${range}`,
    describeEmpty: 'Regel ohne Blattregeln',
    tz: 'Zeitzone',
    zoneMismatch: (rule: string, resource: string) => `Regel in ${rule}, Ressource in ${resource}`,
  },

  inspector: {
    title: 'Regel-Inspektor',
    close: 'Inspektor schließen',
    calendar: 'Kalender',
    resourceZone: 'Zeitzone der Ressource',
    blocks: (n: number) => plural(n, 'Regelblock', 'Regelblöcke'),
    noTree: 'Kein Kalender geladen.',
    noBlocks: 'Dieser Kalender hat keine Regeln.',
    group: (n: number) => `je Wochentag verschieden · ${plural(n, 'Teil', 'Teile')}`,
    fields: 'Felder',
    rawJson: 'Roh-JSON',
    field: 'Feld',
    value: 'Wert',
    rootRule: 'Wurzelregel',
    innerCalendar: 'Innerer Kalender',
    leaves: (n: number) => plural(n, 'Blattregel', 'Blattregeln'),
    rank: 'Rang',
    pattern: 'Muster',
    interval: 'Gültig',
    zone: 'Zeitzone',
    modified: 'Geändert',
    selectBlock: 'Einen Block im Baum wählen, um seine Felder zu sehen.',
    orphans: (n: number) => plural(n, 'verwaister innerer Kalender', 'verwaiste innere Kalender'),
    unparsed: (n: number) => plural(n, 'nicht interpretierbare Regel', 'nicht interpretierbare Regeln'),
    effort: 'Kapazität',
    codes: (t: number | null, s: number | null) => `timecode ${t ?? '–'} / subcode ${s ?? '–'}`,
    treeLabel: 'Regelbaum',
    actions: { newWork: 'Arbeitszeit anlegen', newAbsence: 'Abwesenheit anlegen', newNonwork: 'Nicht-Arbeit anlegen', edit: 'Bearbeiten', end: 'Beenden', delete: 'Löschen', editDay: 'Einzeltag …', readOnly: 'Nur lesen — keine Berechtigung zum Ändern.' },
  },


  editor: {
    titleCreate: 'Arbeitszeit anlegen',
    titleCreateAbsence: 'Abwesenheit anlegen',
    titleEdit: 'Regel bearbeiten',
    titleEditDay: (date: string) => `Einzeltag ${date} bearbeiten`,
    titleEnd: 'Wiederholung beenden',
    titleDelete: 'Regel löschen',
    tabs: { form: 'Eingabe', preview: 'Vorschau' },
    kind: 'Art',
    kinds: { work: 'Arbeitszeit', timeoff: 'Abwesenheit', nonwork: 'Nicht-Arbeit' },
    recurrence: 'Wiederholung',
    recurrences: { once: 'Einmal', weekly: 'Wöchentlich', varied: 'Je Wochentag verschieden' },
    weekdays: 'Wochentage',
    weekdayLabel: (d: number) => ['', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'][d] ?? String(d),
    date: 'Datum',
    startDate: 'Ab',
    endDate: 'Bis (optional)',
    noEnd: 'ohne Ende',
    times: 'Zeiten',
    from: 'von',
    to: 'bis',
    addWork: 'Arbeitszeit hinzufügen',
    addBreak: 'Pause hinzufügen',
    remove: 'Entfernen',
    allDay: 'Ganztägig',
    days: 'Tage',
    effort: 'Kapazität',
    observeClosure: 'Geschäftsschließungen beachten',
    timeZone: 'Zeitzone der Regel',
    reason: 'Grund',
    reasonPlaceholder: 'z. B. Urlaub, Fortbildung',
    scope: 'Gilt für',
    scopes: { series: 'Ganze Wiederholung', following: 'Diesen und folgende Tage ab' },
    lastDay: 'Letzter Tag',
    save: 'Speichern',
    saving: 'Speichere …',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    end: 'Beenden',
    confirmDelete: (what: string) => `„${what}“ wirklich löschen? Die ganze Wiederholung mit allen Blattregeln wird entfernt.`,
    saved: (n: number) => `${plural(n, 'Aufruf', 'Aufrufe')} gespeichert.`,
    deleted: 'Regel gelöscht.',
    requestSave: 'msdyn_SaveCalendar',
    requestDelete: 'msdyn_DeleteCalendar',
    preview: {
      title: 'Betroffene Tage',
      intro: 'So sieht der Kalender nach dem Speichern aus — gerechnet aus den Regeln, nicht aus den Slots des Servers.',
      before: 'Vorher',
      after: 'Nachher',
      noChange: 'Keine Änderung im Vorschauzeitraum.',
      changed: (n: number) => `${plural(n, 'Tag ändert', 'Tage ändern')} sich`,
      requests: 'Aufrufe an die API',
      error: 'Vorschau nicht möglich',
      unchangedHidden: (n: number) => `${plural(n, 'unveränderter Tag ausgeblendet', 'unveränderte Tage ausgeblendet')}`,
    },
    hints: {
      nightShift: 'Ein Zeitraum über Mitternacht wird als zwei Regeln gespeichert (die API erlaubt keine Ereignisse über den Tageswechsel).',
      noAbsenceRecurrence: 'Abwesenheit und Nicht-Arbeit haben keine Wiederholung — mehrere Tage als Ganztag anlegen oder je Tag.',
      noSingleDelete: 'Ein einzelner Tag lässt sich nicht aus einer Wiederholung löschen — stattdessen einen Nicht-Arbeit-Tag anlegen.',
      breaks: 'Pausen liegen zwischen Arbeitszeiten und werden nie allein gespeichert.',
      v2: 'UseV2 ist aktiv: überlappende Wiederholungen bleiben nebeneinander bestehen, im Schnitt gewinnt die zuletzt geänderte.',
      varied: 'Je Wochentag verschieden wird als Gruppe (IsVaried) gespeichert; Löschen entfernt alle Teile.',
    },
    errors: {
      noSegments: 'Mindestens eine Zeit angeben.',
      invalidTime: 'Ungültige Uhrzeit.',
      emptySegment: 'Ende muss nach dem Beginn liegen.',
      overlap: 'Zeiten überschneiden sich.',
      breakAlone: 'Pausen brauchen Arbeitszeit am selben Tag.',
      invalidDate: 'Ungültiges Datum.',
      allDayRecurrence: 'Ganztägige Wiederholungen unterstützt die API nicht.',
      allDayLength: 'Ganztags-Ereignisse dauern 1 Tag bis 5 Jahre.',
      variedNeedsRecurrence: 'Je Wochentag verschieden ist immer eine Wiederholung.',
      noWeekdays: 'Mindestens einen Wochentag wählen.',
      endBeforeStart: 'Das Ende liegt vor dem Beginn.',
      effort: 'Kapazität ist eine ganze Zahl ab 1.',
      noInnerCalendar: 'Diese Regel hat keinen inneren Kalender und kann nicht über die API gelöscht werden.',
      privilege: 'Keine Berechtigung zum Ändern dieses Kalenders — die App ist jetzt nur lesend.',
    },
  },

  findings: {
    noWorkingTime: 'Ohne Arbeitszeit im Zeitraum',
    ruleEnding: 'Regel endet bald / ist ausgelaufen',
    timeZoneMismatch: 'Zeitzone Regel ≠ Ressource',
    inactiveWithBookings: 'Inaktiv, aber mit Buchungen',
    noCalendar: 'Ohne Kalender / ohne Regeln',
    orphanInnerCalendar: 'Verwaister innerer Kalender',
  } satisfies Record<FindingKind, string>,

  findingDetails: {
    noWorkingTime: (from: string, to: string) => `Keine Arbeitszeit zwischen ${from} und ${to}.`,
    ruleEndsIn: (days: number, date: string) => `Wiederholung endet in ${plural(days, 'Tag', 'Tagen')} (${date}); danach keine Arbeitszeit aus dieser Regel.`,
    ruleEnded: (date: string) => `Wiederholung endete am ${date}.`,
    tzMismatch: (rule: string, resource: string) => `Regel in ${rule}, Ressource in ${resource} — die Arbeitszeit verschiebt sich auf dem Board.`,
    inactiveWithBookings: (n: number, date: string) => `${plural(n, 'Buchung', 'Buchungen')} nach dem ${date}.`,
    noCalendar: 'Die Ressource hat keinen Kalender.',
    noRules: 'Der Kalender enthält keine Regeln.',
    orphan: (n: number) => `${plural(n, 'innerer Kalender', 'innere Kalender')} ohne Wurzelregel.`,
  },

  diagnostics: {
    title: 'Diagnose',
    intro: (days: number, ending: number) => `Befunde über alle aktiven Ressourcen: Arbeitszeit in den nächsten ${days} Tagen, Regeln, die in ${ending} Tagen enden, Zeitzonen, inaktive Ressourcen mit Buchungen, Kalender ohne Regeln.`,
    all: 'Alle Befunde',
    none: 'Keine Befunde — alle Ressourcen haben Arbeitszeit, gültige Regeln und passende Zeitzonen.',
    noneForKind: 'Keine Befunde dieser Art.',
    severity: { error: 'Fehler', warning: 'Warnung', info: 'Hinweis' },
    showInCalendar: 'Im Kalender zeigen',
    count: (n: number) => plural(n, 'Befund', 'Befunde'),
    resources: (n: number) => plural(n, 'Ressource', 'Ressourcen'),
    waiting: 'Diagnose läuft, sobald Ressourcen und Regeln geladen sind …',
    basedOn: { slots: 'Grundlage: aufgelöste Slots (msdyn_LoadCalendars) und Regelbäume.', rules: 'Grundlage: Regelbäume (Slots nicht verfügbar).' },
  },

  templates: {
    title: 'Arbeitszeitvorlagen',
    intro: 'Vorlagen haben einen eigenen Kalender und werden mit demselben Editor gepflegt wie Ressourcen. „Vorlage anwenden“ liest ihre Blattregeln und schreibt sie als neue Regeln auf die Ressourcen (Massenlauf).',
    empty: 'Keine Vorlagen vorhanden.',
    inactive: 'inaktiv',
    noCalendar: 'ohne Kalender',
    rules: 'Regeln',
    apply: 'Auf Ressourcen anwenden',
  },

  holidays: {
    title: 'Feiertage & Geschäftsschließungen',
    intro: 'Geschäftsschließungen gelten für die ganze Organisation (Kalender organization.businessclosurecalendarid). Ressourcen, deren Regeln Schließungen beachten, haben an diesen Tagen keine Arbeitszeit.',
    year: 'Jahr',
    columns: { name: 'Name', from: 'Von', to: 'Bis', days: 'Tage' },
    empty: (year: number) => `Keine Schließungen für ${year}.`,
    count: (n: number) => plural(n, 'Schließung', 'Schließungen'),
    national: 'bundesweit',
    regional: 'regional',
    optional: 'nur in Teilen des Landes',
    status: { ok: 'vorhanden', missing: 'fehlt', nameDiffers: 'anderer Name', partial: 'nur teilweise' },
    extra: 'nicht im Regelwerk',
    duplicate: 'doppelt',
    readOnlyHint: 'Anlegen, Abgleich mit dem Regelwerk und Jahr erzeugen folgen in Phase 5.',
  },

  runs: {
    title: 'Läufe',
    empty: 'Noch keine Läufe. Massenaktionen (Vorlage anwenden, Betriebsferien) starten aus der Ressourcenliste über die Auswahl — folgt in Phase 4.',
  },

  setup: {
    title: 'Einrichtung',
    intro: 'Was die Umgebung bereitstellt. Rot = fehlt oder nicht erreichbar; Details in der README unter „Einrichtung“.',
    rerun: 'Erneut prüfen',
    ok: 'OK',
    missing: 'Fehlt',
  },

  plural,
  hours,
} as const
