import type { FindingKind, OriginKind, ResourceType, SegmentKind, WorkHourKind } from './types/calendar'

/**
 * Every UI text in one place (German). Help texts live in
 * `help/helpContent.ts`. Pure functions in `utils/` take their labels from
 * here too, so the wording stays consistent between calendar, inspector
 * and diagnostics.
 */

const plural = (n: number, one: string, many: string) => `${n.toLocaleString('de-DE')} ${n === 1 ? one : many}`
const hours = (h: number) => `${h.toLocaleString('de-DE', { maximumFractionDigits: 2 })} h`

export const S = {
  app: {
    title: 'Arbeitszeiten & Kalender',
    nav: { resources: 'Ressourcen', templates: 'Vorlagen', holidays: 'Feiertage', diagnostics: 'Diagnose', runs: 'Läufe', setup: 'Einrichtung' },
    navLabel: 'Bereiche',
    help: 'Hilfe',
    helpTitle: 'Hilfe zum aktuellen Bereich',
    modeMock: 'Mock-Daten',
    modeDataverse: 'Dataverse',
    modeMockTitle: 'Kein Power-Apps-Host — fiktive Beispieldaten im Speicher',
    loading: 'Lade …',
    treesLoading: (n: number) => `Lade die Regeln von ${n} Kalendern (je Kalender eine Abfrage) — Liste und Stunden stehen schon, Regeln und Befunde folgen.`,
    readOnly: 'Nur lesen',
    readOnlyTitle: 'Speichern wurde wegen fehlender Berechtigung abgelehnt — die App zeigt nur noch an.',
    loadError: (what: string, err: string) => `${what} konnten nicht geladen werden: ${err}`,
    slotsUnavailable: (err: string) => `msdyn_LoadCalendars nicht erreichbar (${err}) — Arbeitszeit wird aus den Regeln abgeleitet, nicht aus den aufgelösten Slots.`,
    reload: 'Neu laden',
  },

  toolbar: {
    week: 'Woche',
    month: 'Monat',
    today: 'Heute',
    prev: 'Zurück',
    next: 'Weiter',
    viewerZone: 'Anzeige-Zeitzone',
    useV2: 'UseV2',
    useV2Title: 'Mehrere Wiederholungen parallel (V2-Überlappungslogik) bei jedem Speichern mitsenden',
    viewMode: 'Ansicht',
  },

  resources: {
    tabs: { list: 'Liste', calendar: 'Kalender' },
    search: 'Ressource suchen …',
    unit: 'Org-Einheit',
    category: 'Kategorie',
    territory: 'Gebiet',
    showInactive: 'Inaktive zeigen',
    onlyFindings: 'Nur mit Befunden',
    columns: { name: 'Name', type: 'Typ', unit: 'Org-Einheit', categories: 'Kategorien', zone: 'Zeitzone', status: 'Status', findings: 'Befunde', week: 'Stunden', rules: 'Regeln' },
    active: 'Aktiv',
    inactive: 'Inaktiv',
    noCalendar: 'kein Kalender',
    rulesCount: (n: number) => plural(n, 'Regel', 'Regeln'),
    selected: (n: number) => `${plural(n, 'Ressource', 'Ressourcen')} gewählt`,
    clearSelection: 'Auswahl aufheben',
    empty: 'Keine Ressourcen gefunden.',
    emptyEnv: 'Keine Ressourcen sichtbar. Hat die Umgebung Field Service / URS, und hat das Konto Leserecht auf „Buchbare Ressource“?',
    showDetails: 'Details anzeigen',
    selectAll: 'Alle wählen',
    selectRow: 'Wählen',
    openForm: 'In Dynamics öffnen',
    hoursInRange: hours,
    capacity: (h: number) => `Kapazität ${hours(h)}`,
  },

  calendar: {
    week: 'Wochenansicht',
    month: 'Monatsansicht',
    pickResource: 'Für die Monatsansicht eine Ressource in der Liste anklicken (Details).',
    noResources: 'Keine Ressource im Filter.',
    hours: hours,
    noWork: 'keine Arbeitszeit',
    total: 'Summe',
    legend: 'Legende',
    origin: 'Herkunft',
    rule: 'Regel',
    showRule: 'Regel im Inspektor zeigen',
    editDay: 'Diesen Tag ändern',
    addAbsence: 'Abwesenheit an diesem Tag',
    addWork: 'Arbeitszeit an diesem Tag',
    derived: 'aus Regeln abgeleitet',
    fromSlots: 'aus msdyn_LoadCalendars',
    closedDay: 'Schließung',
    slotCount: (n: number) => plural(n, 'Slot', 'Slots'),
    dayTitle: (date: string, h: string) => `${date} · ${h}`,
    effort: (e: number) => `Kapazität ${e}`,
    outsideMonth: 'anderer Monat',
    todayMark: 'Heute',
  },

  kinds: {
    work: 'Arbeitszeit',
    break: 'Pause',
    nonwork: 'Nicht-Arbeit',
    timeoff: 'Abwesenheit',
    closure: 'Geschäftsschließung',
    unknown: 'Unbekannt',
  } satisfies Record<WorkHourKind, string>,

  segments: {
    work: 'Arbeitszeit',
    break: 'Pause',
    timeoff: 'Abwesenheit',
    nonwork: 'Nicht-Arbeit',
    closure: 'Schließung',
  } satisfies Record<SegmentKind, string>,

  origins: {
    recurrence: 'Wiederholung',
    occurrence: 'Einzeltag',
    break: 'Pause',
    timeoff: 'Abwesenheit',
    nonwork: 'Nicht-Arbeit',
    closure: 'Schließung',
    slot: 'Arbeitszeit (Regel unbekannt)',
  } satisfies Record<OriginKind, string>,

  reasons: {
    none: '',
    timeoff: 'Abwesenheit',
    closure: 'Geschäftsschließung',
    nonwork: 'Nicht-Arbeit',
    noRule: 'Keine Arbeitszeitregel',
    ruleEnded: 'Regel ausgelaufen',
    ruleNotStarted: 'Regel beginnt später',
    weekdayOff: 'Kein Arbeitstag',
  },

  resourceTypes: {
    generic: 'Generisch',
    contact: 'Kontakt',
    user: 'Benutzer',
    equipment: 'Ausrüstung',
    account: 'Firma',
    crew: 'Team',
    facility: 'Einrichtung',
    pool: 'Pool',
  } satisfies Record<ResourceType, string>,

  rules: {
    weekly: 'Wöchentlich',
    daily: 'Täglich',
    once: 'Einmal',
    allDay: 'ganztägig',
    varied: 'je Wochentag verschieden',
    openEnd: 'ohne Ende',
    from: 'ab',
    until: 'bis',
    capacity: 'Kapazität',
    rankInfo: 'Rang der Wurzelregel (Server) — der kleinere gewinnt: 0 Einzeltag, 1 Feiertagsliste, 2 wöchentliche Wiederholung. Ob eine Regel wiederkehrt, entscheidet das Muster.',
    holidayList: (n: number, loaded: boolean, from: string, until: string | null) => `Feiertagsliste${loaded ? ` · ${n} ${n === 1 ? 'Feiertag' : 'Feiertage'}` : ''} · ab ${from}${until ? ` bis ${until}` : ''}`,
    root: 'Wurzelregel',
    inner: 'Innerer Kalender',
    leaf: 'Blattregel',
    orphan: 'Verwaister innerer Kalender',
    unparsed: 'Nicht interpretierbare Regel',
    ends: (date: string) => `endet ${date}`,
    ended: (date: string) => `endete ${date}`,
    pauseAt: (range: string) => `Pause ${range}`,
    describeEmpty: 'Regel ohne Blattregeln',
    tz: 'Zeitzone',
    zoneMismatch: (rule: string, resource: string) => `Regel in ${rule}, Ressource in ${resource}`,
  },

  inspector: {
    title: 'Regel-Inspektor',
    close: 'Inspektor schließen',
    calendar: 'Kalender',
    resourceZone: 'Zeitzone der Ressource',
    blocks: (n: number) => plural(n, 'Regelblock', 'Regelblöcke'),
    noTree: 'Kein Kalender geladen.',
    loadingTree: 'Lade Regeln und innere Kalender …',
    holiday: 'Feiertag',
    holidays: 'Feiertage',
    treeError: (err: string) => `Regeln nicht ladbar: ${err}`,
    noBlocks: 'Dieser Kalender hat keine Regeln.',
    group: (n: number) => `je Wochentag verschieden · ${plural(n, 'Teil', 'Teile')}`,
    fields: 'Felder',
    rawJson: 'Roh-JSON',
    field: 'Feld',
    value: 'Wert',
    rootRule: 'Wurzelregel',
    innerCalendar: 'Innerer Kalender',
    leaves: (n: number) => plural(n, 'Blattregel', 'Blattregeln'),
    rank: 'Rang',
    pattern: 'Muster',
    interval: 'Gültig',
    zone: 'Zeitzone',
    modified: 'Geändert',
    selectBlock: 'Einen Block im Baum wählen, um seine Felder zu sehen.',
    orphans: (n: number) => plural(n, 'verwaister innerer Kalender', 'verwaiste innere Kalender'),
    unparsed: (n: number) => plural(n, 'nicht interpretierbare Regel', 'nicht interpretierbare Regeln'),
    effort: 'Kapazität',
    codes: (t: number | null, s: number | null) => `timecode ${t ?? '–'} / subcode ${s ?? '–'}`,
    treeLabel: 'Regelbaum',
    actions: { newWork: 'Arbeitszeit anlegen', newAbsence: 'Abwesenheit anlegen', newNonwork: 'Nicht-Arbeit anlegen', edit: 'Bearbeiten', end: 'Beenden', delete: 'Löschen', editDay: 'Einzeltag …', readOnly: 'Nur lesen — keine Berechtigung zum Ändern.' },
  },


  editor: {
    titleCreate: 'Arbeitszeit anlegen',
    titleCreateAbsence: 'Abwesenheit anlegen',
    titleEdit: 'Regel bearbeiten',
    titleEditDay: (date: string) => `Einzeltag ${date} bearbeiten`,
    titleEnd: 'Wiederholung beenden',
    titleDelete: 'Regel löschen',
    tabs: { form: 'Eingabe', preview: 'Vorschau' },
    kind: 'Art',
    kinds: { work: 'Arbeitszeit', timeoff: 'Abwesenheit', nonwork: 'Nicht-Arbeit' },
    recurrence: 'Wiederholung',
    recurrences: { once: 'Einmal', weekly: 'Wöchentlich', varied: 'Je Wochentag verschieden' },
    weekdays: 'Wochentage',
    weekdayLabel: (d: number) => ['', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'][d] ?? String(d),
    date: 'Datum',
    startDate: 'Ab',
    endDate: 'Bis (optional)',
    noEnd: 'ohne Ende',
    times: 'Zeiten',
    from: 'von',
    to: 'bis',
    addWork: 'Arbeitszeit hinzufügen',
    addBreak: 'Pause hinzufügen',
    remove: 'Entfernen',
    allDay: 'Ganztägig',
    days: 'Tage',
    effort: 'Kapazität',
    observeClosure: 'Geschäftsschließungen beachten',
    timeZone: 'Zeitzone der Regel',
    reason: 'Grund',
    reasonPlaceholder: 'z. B. Urlaub, Fortbildung',
    scope: 'Gilt für',
    scopes: { series: 'Ganze Wiederholung', following: 'Diesen und folgende Tage ab' },
    lastDay: 'Letzter Tag',
    save: 'Speichern',
    saving: 'Speichere …',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    end: 'Beenden',
    confirmDelete: (what: string, recurring: boolean) => `„${what}“ wirklich löschen? ${recurring ? 'Die ganze Wiederholung mit allen Blattregeln wird entfernt.' : 'Die Regel mit allen Blattregeln wird entfernt.'}`,
    saved: (n: number) => `${plural(n, 'Aufruf', 'Aufrufe')} gespeichert.`,
    deleted: 'Regel gelöscht.',
    requestSave: 'msdyn_SaveCalendar',
    requestDelete: 'msdyn_DeleteCalendar',
    preview: {
      title: 'Betroffene Tage',
      intro: 'So sieht der Kalender nach dem Speichern aus — gerechnet aus den Regeln, nicht aus den Slots des Servers.',
      before: 'Vorher',
      after: 'Nachher',
      noChange: 'Keine Änderung im Vorschauzeitraum.',
      changed: (n: number) => `${plural(n, 'Tag ändert', 'Tage ändern')} sich`,
      requests: 'Aufrufe an die API',
      error: 'Vorschau nicht möglich',
      unchangedHidden: (n: number) => `${plural(n, 'unveränderter Tag ausgeblendet', 'unveränderte Tage ausgeblendet')}`,
    },
    hints: {
      nightShift: 'Ein Zeitraum über Mitternacht wird als zwei Regeln gespeichert (die API erlaubt keine Ereignisse über den Tageswechsel).',
      noAbsenceRecurrence: 'Abwesenheit und Nicht-Arbeit haben keine Wiederholung — mehrere Tage als Ganztag anlegen oder je Tag.',
      noSingleDelete: 'Ein einzelner Tag lässt sich nicht aus einer Wiederholung löschen — stattdessen einen Nicht-Arbeit-Tag anlegen.',
      breaks: 'Pausen liegen zwischen Arbeitszeiten und werden nie allein gespeichert.',
      v2: 'Überschneidet sich die neue Wiederholung mit einer bestehenden, nimmt der Server ihr ab dem Startdatum die gemeinsamen Wochentage weg — die alte Regel endet am Vortag, ihre übrigen Wochentage laufen als neue Regel weiter.',
      varied: 'Je Wochentag verschieden wird als einzelne Regeln je Zeitmuster gespeichert (IsVaried); jede lässt sich danach einzeln bearbeiten und löschen.',
    },
    errors: {
      noSegments: 'Mindestens eine Zeit angeben.',
      invalidTime: 'Ungültige Uhrzeit.',
      emptySegment: 'Ende muss nach dem Beginn liegen.',
      overlap: 'Zeiten überschneiden sich.',
      breakAlone: 'Pausen brauchen Arbeitszeit am selben Tag.',
      invalidDate: 'Ungültiges Datum.',
      allDayRecurrence: 'Ganztägige Wiederholungen unterstützt die API nicht.',
      allDayLength: 'Ganztags-Ereignisse dauern 1 Tag bis 5 Jahre.',
      variedNeedsRecurrence: 'Je Wochentag verschieden ist immer eine Wiederholung.',
      noWeekdays: 'Mindestens einen Wochentag wählen.',
      endBeforeStart: 'Das Ende liegt vor dem Beginn.',
      effort: 'Kapazität ist eine ganze Zahl ab 1.',
      noInnerCalendar: 'Diese Regel hat keinen inneren Kalender und kann nicht über die API gelöscht werden.',
      privilege: 'Keine Berechtigung zum Ändern dieses Kalenders — die App ist jetzt nur lesend.',
    },
  },

  findings: {
    noWorkingTime: 'Ohne Arbeitszeit im Zeitraum',
    ruleEnding: 'Regel endet bald / ist ausgelaufen',
    timeZoneMismatch: 'Zeitzone Regel ≠ Ressource',
    inactiveWithBookings: 'Inaktiv, aber mit Buchungen',
    noCalendar: 'Ohne Kalender / ohne Regeln',
    orphanInnerCalendar: 'Verwaister innerer Kalender',
  } satisfies Record<FindingKind, string>,

  findingDetails: {
    noWorkingTime: (from: string, to: string) => `Keine Arbeitszeit zwischen ${from} und ${to}.`,
    ruleEndsIn: (days: number, date: string) => `Wiederholung endet in ${plural(days, 'Tag', 'Tagen')} (${date}); danach keine Arbeitszeit aus dieser Regel.`,
    ruleEnded: (date: string) => `Wiederholung endete am ${date}.`,
    tzMismatch: (rule: string, resource: string) => `Regel in ${rule}, Ressource in ${resource} — das Board zeigt die Zeiten der Regel; neue Regeln (Editor, Vorlage) entstehen in der Zeitzone der Ressource und liegen dann verschoben.`,
    inactiveWithBookings: (n: number, date: string) => `${plural(n, 'Buchung', 'Buchungen')} nach dem ${date}.`,
    noCalendar: 'Die Ressource hat keinen Kalender.',
    noRules: 'Der Kalender enthält keine Regeln.',
    orphan: (n: number) => `${plural(n, 'innerer Kalender', 'innere Kalender')} ohne Wurzelregel.`,
  },

  diagnostics: {
    title: 'Diagnose',
    intro: (days: number, ending: number) => `Befunde über alle aktiven Ressourcen: Arbeitszeit in den nächsten ${days} Tagen, Regeln, die in ${ending} Tagen enden, Zeitzonen, inaktive Ressourcen mit Buchungen, Kalender ohne Regeln.`,
    all: 'Alle Befunde',
    none: 'Keine Befunde — alle Ressourcen haben Arbeitszeit, gültige Regeln und passende Zeitzonen.',
    noneForKind: 'Keine Befunde dieser Art.',
    severity: { error: 'Fehler', warning: 'Warnung', info: 'Hinweis' },
    showInCalendar: 'Im Kalender zeigen',
    count: (n: number) => plural(n, 'Befund', 'Befunde'),
    resources: (n: number) => plural(n, 'Ressource', 'Ressourcen'),
    waiting: 'Diagnose läuft, sobald Ressourcen und Regeln geladen sind …',
    basedOn: { slots: 'Grundlage: aufgelöste Slots (msdyn_LoadCalendars) und Regelbäume.', rules: 'Grundlage: Regelbäume (Slots nicht verfügbar).' },
  },

  templates: {
    title: 'Arbeitszeitvorlagen',
    intro: 'Vorlagen haben einen eigenen Kalender und werden mit demselben Editor gepflegt wie Ressourcen. „Vorlage anwenden“ liest ihre Blattregeln und schreibt sie als neue Regeln auf die Ressourcen (Massenlauf).',
    empty: 'Keine Vorlagen vorhanden.',
    inactive: 'inaktiv',
    noCalendar: 'ohne Kalender',
    rules: 'Regeln',
    apply: 'Auf Ressourcen anwenden',
  },

  holidays: {
    title: 'Feiertage & Geschäftsschließungen',
    intro: 'Geschäftsschließungen gelten für die ganze Organisation (Kalender organization.businessclosurecalendarid). Ressourcen, deren Regeln Schließungen beachten, haben an diesen Tagen keine Arbeitszeit.',
    year: 'Jahr',
    empty: (year: number) => `Keine Schließungen für ${year}.`,
    count: (n: number) => plural(n, 'Schließung', 'Schließungen'),
    national: 'bundesweit',
    regional: 'regional',
    optional: 'nur in Teilen des Landes',
    status: { ok: 'vorhanden', missing: 'fehlt', nameDiffers: 'anderer Name', partial: 'nur teilweise' },
    extra: 'nicht im Regelwerk',
    duplicate: 'doppelt',
    closuresTitle: (year: number) => `Schließungen ${year}`,
    newClosure: 'Neue Schließung',
    name: 'Name',
    namePlaceholder: 'z. B. Betriebsferien',
    date: 'Erster Tag',
    days: 'Tage',
    create: 'Anlegen',
    creating: 'Lege an …',
    delete: 'Löschen',
    confirmDelete: (name: string) => `Schließung „${name}“ löschen? Ressourcen, die Schließungen beachten, bekommen den Tag als Arbeitszeit zurück.`,
    deleteFailedHint: 'Löschen wurde abgelehnt (msdyn_BusinessClosureDelete) — Berechtigung prüfen oder die Schließung im Admin-Center unter Geschäftsschließungen löschen.',
    created: (n: number) => `${plural(n, 'Schließung', 'Schließungen')} angelegt.`,
    deleted: 'Schließung gelöscht.',
    ruleset: 'Regelwerk',
    reconcileTitle: 'Abgleich mit dem Regelwerk',
    reconcileIntro: 'Die Feiertage des gewählten Regelwerks gegen die Schließungen der Organisation: vorhanden, fehlt, anderer Name, nur teilweise. Fehlende lassen sich markieren und in einem Schritt anlegen (je Feiertag ein Aufruf von msdyn_BusinessClosureSave, ganztägig in der Anzeige-Zeitzone).',
    columns: { name: 'Name', from: 'Von', to: 'Bis', days: 'Tage', date: 'Datum', scope: 'Gilt', status: 'Status', closure: 'Schließung' },
    selectMissing: 'Alle fehlenden wählen',
    createMissing: (n: number) => `${plural(n, 'fehlende Schließung', 'fehlende Schließungen')} anlegen`,
    extras: (n: number) => `${plural(n, 'Schließung', 'Schließungen')} außerhalb des Regelwerks`,
    duplicates: (n: number) => `${plural(n, 'Tag', 'Tage')} doppelt belegt`,
    readOnly: 'Nur lesen — keine Berechtigung zum Ändern.',
    allPresent: 'Alle Feiertage des Regelwerks sind als Schließung vorhanden.',
    summary: (ok: number, missing: number, differs: number) => `${ok} vorhanden · ${missing} fehlen · ${differs} abweichend`,
  },

  runs: {
    title: 'Läufe',
    empty: 'Noch keine Läufe. Massenaktionen (Vorlage anwenden, Abwesenheit für mehrere) starten aus der Ressourcenliste über die Auswahl.',
    intro: 'Jeder Lauf beginnt mit einem Snapshot der betroffenen Kalender. Rückgängig ist ein normaler Lauf mit Vorschau: löscht, was der Lauf angelegt hat, und stellt beendete oder gelöschte Regeln aus dem Snapshot wieder her. Verlauf lokal im Browser, die letzten 20.',
    start: 'Massenaktion …',
    wizardTitle: 'Massenaktion',
    steps: { targets: 'Ressourcen', action: 'Aktion', preview: 'Vorschau', run: 'Ausführen' },
    next: 'Weiter',
    back: 'Zurück',
    execute: 'Ausführen',
    executing: 'Läuft …',
    abort: 'Abbrechen',
    close: 'Schließen',
    done: 'Fertig',
    targetsIntro: (n: number, max: number) => `${plural(n, 'Ressource', 'Ressourcen')} gewählt (max. ${max} je Lauf).`,
    tooMany: (max: number) => `Mehr als ${max} Ressourcen gewählt — nur die ersten ${max} laufen; den Rest in einem zweiten Lauf.`,
    noTargets: 'Zuerst Ressourcen in der Liste auswählen.',
    actionKind: 'Was soll passieren?',
    actions: { applyTemplate: 'Vorlage anwenden', timeOff: 'Abwesenheit / Nicht-Arbeit anlegen' },
    template: 'Vorlage',
    templatePlaceholder: 'Vorlage wählen …',
    cutoff: 'Gilt ab',
    endExisting: 'Bestehende Wiederholungen am Vortag beenden',
    endExistingHint: 'Aus: der Server nimmt den bestehenden Wiederholungen nur die Wochentage der Vorlage weg, übrige Wochentage laufen weiter. An: alte Wiederholungen enden am Vortag, spätere werden gelöscht.',
    previewColumns: { resource: 'Ressource', before: 'Vorher (h/Woche)', after: 'Nachher (h/Woche)', rules: 'Regeln', status: 'Status', note: 'Hinweis' },
    status: { change: 'ändert', skipped: 'übersprungen', done: 'erledigt', failed: 'Fehler', pending: 'wartet', aborted: 'abgebrochen' },
    counts: (change: number, skipped: number) => `${plural(change, 'Ressource ändert sich', 'Ressourcen ändern sich')}, ${skipped} übersprungen`,
    requestsTotal: (n: number) => `${plural(n, 'Aufruf', 'Aufrufe')} an die API`,
    progress: (i: number, n: number) => `${i} von ${n}`,
    resultOk: (n: number) => `${plural(n, 'Ressource', 'Ressourcen')} geschrieben.`,
    resultFailed: (name: string) => `Abbruch bei „${name}“ — alles davor ist geschrieben, der Rest nicht. Verlauf und Rückgängig zeigen den Stand.`,
    resultAborted: 'Abgebrochen — alles bis dahin ist geschrieben, der Rest nicht.',
    skipNoCalendar: 'kein Kalender',
    skipNothing: 'nichts zu tun',
    skipError: 'Vorschau fehlgeschlagen',
    skipTemplateEmpty: 'Vorlage hat keine Wiederholung',
    templateIgnored: (n: number) => `${plural(n, 'Regel der Vorlage ignoriert', 'Regeln der Vorlage ignoriert')} (nur wöchentliche Arbeitszeit wird übertragen)`,
    noteEnded: (n: number) => `${plural(n, 'Wiederholung endet', 'Wiederholungen enden')} am Vortag`,
    noteDeleted: (n: number) => `${plural(n, 'spätere Wiederholung gelöscht', 'spätere Wiederholungen gelöscht')}`,
    noteCreated: (n: number) => `${plural(n, 'Regel aus der Vorlage', 'Regeln aus der Vorlage')}`,
    noteAbsence: (days: number) => `${plural(days, 'Tag', 'Tage')} Abwesenheit`,
    labelTemplate: (name: string) => `Vorlage „${name}“ anwenden`,
    labelTimeOff: (reason: string) => `Abwesenheit „${reason}“`,
    labelNonwork: 'Nicht-Arbeit',
    labelUndo: (label: string) => `Rückgängig: ${label}`,
    summaryTemplate: (name: string, cutoff: string, n: number, endExisting: boolean) => `${name} ab ${cutoff} auf ${plural(n, 'Ressource', 'Ressourcen')}${endExisting ? ', bestehende Wiederholungen beendet' : ''}`,
    summaryAbsence: (date: string, days: number, n: number) => `ab ${date}, ${plural(days, 'Tag', 'Tage')}, ${plural(n, 'Ressource', 'Ressourcen')}`,
    summaryUndo: (label: string, at: string) => `macht „${label}“ vom ${at} rückgängig`,
    undoSkipNotDone: 'im Lauf nicht geschrieben',
    undoNothing: 'nichts wiederherzustellen',
    undoNoteDelete: (n: number) => `${plural(n, 'angelegte Regel löschen', 'angelegte Regeln löschen')}`,
    undoNoteRestore: (n: number) => `${plural(n, 'Ende wiederherstellen', 'Enden wiederherstellen')}`,
    undoNoteRecreate: (n: number) => `${plural(n, 'gelöschte Regel neu anlegen', 'gelöschte Regeln neu anlegen')}`,
    aborted: 'abgebrochen',
    history: 'Verlauf',
    undo: 'Rückgängig',
    undone: 'rückgängig gemacht',
    download: 'JSON herunterladen',
    stepsOf: (done: number, total: number) => `${done} von ${total} Ressourcen geschrieben`,
    at: (when: string) => `am ${when}`,
  },

  setup: {
    title: 'Einrichtung',
    intro: 'Was die Umgebung bereitstellt. Rot = fehlt oder nicht erreichbar; Details in der README unter „Einrichtung“.',
    build: (iso: string) => `Build ${iso === 'dev' ? 'lokal (dev)' : new Date(iso).toLocaleString('de-DE')}`,
    rerun: 'Erneut prüfen',
    ok: 'OK',
    missing: 'Fehlt',
  },

  plural,
  hours,
} as const
