import type { ApprovalRequest } from '../types/approval'

/**
 * Sample approvals spanning several source systems. These mirror the shape of
 * records you'd later get from real connectors (Power Automate Approvals,
 * Dataverse, finance backends, …) so swapping in a live service is mechanical.
 */
export const mockApprovals: ApprovalRequest[] = [
  {
    id: 'LV-1042',
    title: 'Annual leave – 5 days',
    category: 'Leave',
    status: 'Pending',
    priority: 'Low',
    requester: { name: 'Mara Klein', email: 'mara.klein@contoso.com', initials: 'MK' },
    source: 'Power Automate Approvals',
    submittedOn: '2026-06-02',
    dueOn: '2026-06-09',
    description: 'Vacation from 2026-07-14 to 2026-07-18 (5 working days).',
    details: [
      { label: 'From', value: '2026-07-14' },
      { label: 'To', value: '2026-07-18' },
      { label: 'Remaining balance', value: '17 days' },
    ],
  },
  {
    id: 'PO-8831',
    title: 'Purchase order – 12× monitors',
    category: 'PurchaseOrder',
    status: 'Pending',
    priority: 'Medium',
    requester: { name: 'Tom Berger', email: 'tom.berger@contoso.com', initials: 'TB' },
    source: 'Dataverse',
    submittedOn: '2026-06-03',
    dueOn: '2026-06-07',
    description: 'Replacement monitors for the design team (27", USB-C).',
    amount: 4188,
    details: [
      { label: 'Vendor', value: 'TechSupply GmbH' },
      { label: 'Quantity', value: '12' },
      { label: 'Cost center', value: 'CC-DESIGN-04' },
    ],
  },
  {
    id: 'INV-5570',
    title: 'Invoice – Cloud hosting May',
    category: 'Invoice',
    status: 'Pending',
    priority: 'High',
    requester: { name: 'Sofia Reyes', email: 'sofia.reyes@contoso.com', initials: 'SR' },
    source: 'SAP (custom connector)',
    submittedOn: '2026-06-01',
    dueOn: '2026-06-06',
    description: 'Monthly cloud infrastructure invoice, due on receipt.',
    amount: 18750,
    details: [
      { label: 'Vendor', value: 'Northwind Cloud' },
      { label: 'Invoice #', value: 'NW-2026-0512' },
      { label: 'Payment terms', value: 'Net 5' },
    ],
  },
  {
    id: 'EXP-2290',
    title: 'Expense report – Client trip Berlin',
    category: 'Expense',
    status: 'Pending',
    priority: 'Medium',
    requester: { name: 'Jonas Weiß', email: 'jonas.weiss@contoso.com', initials: 'JW' },
    source: 'Power Automate Approvals',
    submittedOn: '2026-06-04',
    dueOn: '2026-06-11',
    description: 'Travel, hotel and meals for the Q2 client workshop.',
    amount: 932,
    details: [
      { label: 'Trip', value: 'Berlin, 2026-05-26 → 05-28' },
      { label: 'Receipts', value: '6 attached' },
      { label: 'Policy check', value: 'Within limits' },
    ],
  },
  {
    id: 'ACC-3315',
    title: 'Access request – Finance SharePoint',
    category: 'Access',
    status: 'Pending',
    priority: 'High',
    requester: { name: 'Aisha Noor', email: 'aisha.noor@contoso.com', initials: 'AN' },
    source: 'Entra ID (Graph)',
    submittedOn: '2026-06-05',
    dueOn: '2026-06-06',
    description: 'Contributor access to the Finance reporting SharePoint site.',
    details: [
      { label: 'Resource', value: 'Finance Reports (SPO)' },
      { label: 'Role', value: 'Contributor' },
      { label: 'Justification', value: 'Quarterly close support' },
    ],
  },
  {
    id: 'PO-8840',
    title: 'Purchase order – Conference tickets',
    category: 'PurchaseOrder',
    status: 'Pending',
    priority: 'Low',
    requester: { name: 'Leo Fischer', email: 'leo.fischer@contoso.com', initials: 'LF' },
    source: 'Dataverse',
    submittedOn: '2026-06-05',
    dueOn: '2026-06-13',
    description: '3 tickets for the Power Platform Community Conference.',
    amount: 2370,
    details: [
      { label: 'Event', value: 'PPCC 2026' },
      { label: 'Attendees', value: '3' },
      { label: 'Cost center', value: 'CC-ENG-01' },
    ],
  },
]
