import { ORG_URL } from '../config'

/**
 * Access to Dataverse without compile-time dependency on `src/generated/`.
 *
 * The generated clients are gitignored and environment-specific. Loading them
 * through `import.meta.glob` keeps `npm run build` green on a fresh clone
 * (the glob is simply empty) and lets the setup page say which pieces are
 * wired up instead of the build failing with "Cannot find module".
 *
 * Two routes per action, tried in order and remembered once one works:
 * 1. **native** — a service generated by `pa app add dataverse-api --api-name
 *    <Action>` (runs as the signed-in user, POST to the Web API). Needed for
 *    `ExportTranslation`, which Microsoft documents as bound to the
 *    `solution` collection; the connector's "unbound action" may not reach it.
 * 2. **connector** — `PerformUnboundActionWithOrganization` of the Dataverse
 *    connector (`shared_commondataserviceforapps`, user connection).
 */

type OperationResult = { success?: boolean; data?: unknown; value?: unknown; error?: unknown }
type Operation = (...args: unknown[]) => Promise<OperationResult>
type ServiceModule = Record<string, Record<string, Operation> | undefined>

const modules = import.meta.glob<ServiceModule>('../generated/services/*Service.ts', { eager: true })

function generated(service: string): Record<string, Operation> | null {
  for (const [path, mod] of Object.entries(modules)) {
    if (path.endsWith(`/${service}.ts`)) return mod[service] ?? null
  }
  return null
}

export const CONNECTOR_SERVICE = 'MicrosoftDataverseService'

export function hasConnector(): boolean {
  return generated(CONNECTOR_SERVICE) !== null
}

/** Native action services present in `src/generated/`. */
export function nativeActions(names: string[]): Record<string, boolean> {
  return Object.fromEntries(names.map((n) => [n, typeof generated(`${n}Service`)?.[n] === 'function']))
}

export class DataverseError extends Error {
  /** True when the message points to a missing privilege. */
  readonly privilege: boolean
  constructor(message: string) {
    super(message)
    this.privilege = /privilege|prv[A-Z]|0x80040220|0x8004801c|not have (the )?permission|keine berechtigung/i.test(message)
  }
}

function errorText(err: unknown): string {
  if (!err) return 'unbekannter Fehler'
  if (typeof err === 'string') return err
  if (err instanceof Error) return err.message
  const e = err as { message?: unknown; error?: { message?: unknown } }
  if (typeof e.message === 'string') return e.message
  if (typeof e.error?.message === 'string') return e.error.message
  try {
    return JSON.stringify(err)
  } catch {
    return String(err)
  }
}

async function run(op: Operation, args: unknown[]): Promise<unknown> {
  let res: OperationResult
  try {
    res = await op(...args)
  } catch (err) {
    throw new DataverseError(errorText(err))
  }
  if (res && res.success === false) throw new DataverseError(errorText(res.error))
  return res?.data ?? res?.value ?? null
}

function connector(): Record<string, Operation> {
  const svc = generated(CONNECTOR_SERVICE)
  if (!svc) throw new DataverseError('Der Dataverse-Konnektor ist nicht eingebunden (src/generated fehlt, siehe README „Einrichtung“).')
  if (!ORG_URL) throw new DataverseError('VITE_ORG_URL ist nicht gesetzt (.env beim Build).')
  return svc
}

export type Row = Record<string, unknown>

const ANNOTATIONS = 'odata.include-annotations="*"'

/** FetchXML read through the connector (`ListRecordsWithOrganization`, 11th parameter). */
export async function fetchXml(entitySet: string, xml: string, annotations = false): Promise<Row[]> {
  const svc = connector()
  const data = await run(svc.ListRecordsWithOrganization, [ORG_URL, entitySet, annotations ? ANNOTATIONS : undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, xml])
  return ((data as { value?: Row[] } | null)?.value ?? []) as Row[]
}

/** OData read through the connector ($select/$filter/$expand). */
export async function odata(entitySet: string, select: string, filter?: string, expand?: string): Promise<Row[]> {
  const svc = connector()
  const data = await run(svc.ListRecordsWithOrganization, [ORG_URL, entitySet, undefined, undefined, undefined, undefined, select, filter, undefined, expand])
  return ((data as { value?: Row[] } | null)?.value ?? []) as Row[]
}

export type Route = 'native' | 'connector' | 'connector-bound'

const workingRoute = new Map<string, Route>()

export interface ActionSpec {
  name: string
  /** Parameters in the documented order (positional for the native service). */
  params: [string, unknown][]
  /** Collection the action is bound to, e.g. `solutions` (third route). */
  boundTo?: string
  /**
   * The action changes something (import, publish). Such a call may have run
   * on the server even though the client saw an error (timeout, dropped
   * connection) — so another route is only tried when this one provably
   * doesn't exist, never after an error of the call itself.
   */
  sideEffects?: boolean
}

/**
 * Errors that mean "this route can't address the action" — the request never
 * reached it: the connector's "No HTTP resource found" for a GET function or a
 * bound action (solution-forge gotcha #8), an unknown segment, 404.
 */
const ROUTE_UNAVAILABLE =
  /no http resource|resource not found for the segment|not found for the segment|0x8006088a|\b404\b|could not find (a|an) (action|operation|function)|is not a valid (action|operation)|unbound action .* (not|cannot)|does not support (the )?(operation|action)/i

export function routeUnavailable(message: string): boolean {
  return ROUTE_UNAVAILABLE.test(message)
}

/**
 * Whether a failed route may be followed by the next one. Never after a
 * privilege error (another route won't grant rights); for actions with side
 * effects only when the route provably wasn't there.
 */
export function mayTryNextRoute(spec: Pick<ActionSpec, 'sideEffects'>, err: unknown): boolean {
  if (err instanceof DataverseError && err.privilege) return false
  if (!spec.sideEffects) return true
  return routeUnavailable(errorText(err))
}

/**
 * Calls a Dataverse action over the first route that works (see
 * {@link mayTryNextRoute} for when a failure stops the search).
 */
export async function callAction(spec: ActionSpec): Promise<{ data: unknown; route: Route }> {
  const routes: Route[] = ['native', 'connector', ...(spec.boundTo ? (['connector-bound'] as Route[]) : [])]
  const known = workingRoute.get(spec.name)
  const order = known ? [known, ...routes.filter((r) => r !== known)] : routes
  const errors: string[] = []
  for (const route of order) {
    let op: Operation | undefined
    let args: unknown[]
    if (route === 'native') {
      op = generated(`${spec.name}Service`)?.[spec.name]
      args = spec.params.map(([, v]) => v)
    } else {
      if (!generated(CONNECTOR_SERVICE) || !ORG_URL) continue
      op = generated(CONNECTOR_SERVICE)!.PerformUnboundActionWithOrganization
      const actionName = route === 'connector' ? spec.name : `${spec.boundTo}/Microsoft.Dynamics.CRM.${spec.name}`
      args = [ORG_URL, actionName, Object.fromEntries(spec.params)]
    }
    if (typeof op !== 'function') continue
    try {
      const data = await run(op, args)
      workingRoute.set(spec.name, route)
      return { data, route }
    } catch (err) {
      if (!mayTryNextRoute(spec, err)) throw err instanceof DataverseError ? err : new DataverseError(errorText(err))
      errors.push(`${route}: ${errorText(err)}`)
    }
  }
  if (errors.length === 0) throw new DataverseError(`${spec.name}: weder native Aktion noch Konnektor eingebunden (siehe Einrichtung).`)
  console.warn(`[translation] ${spec.name} failed on every route`, errors)
  throw new DataverseError(`${spec.name}: ${errors.join(' · ')}`)
}

/** Finds a property in an action response, wherever the client nested it. */
export function pick(data: unknown, name: string): unknown {
  let cur: unknown = data
  for (let depth = 0; depth < 3 && cur && typeof cur === 'object'; depth++) {
    const obj = cur as Record<string, unknown>
    if (name in obj) return obj[name]
    cur = obj.value ?? obj.data
  }
  return undefined
}
