import type {
  AttributeChange,
  AuditEvent,
  AuditOperation,
  AuditedTable,
} from '../types/audit'
import { mockAuditService } from './mockAuditService'
import { AuditsService } from '../generated/services/AuditsService'
import { RetrieveAuditDetailsService } from '../generated/services/RetrieveAuditDetailsService'
import type { Audits } from '../generated/models/AuditsModel'

/**
 * Real implementation of {@link AuditService} backed by the Dataverse `audit`
 * table and the `RetrieveAuditDetails` function. It auto-falls back to the
 * mock service on any runtime error, so local `npm run dev` outside the Power
 * Platform host still produces a usable dashboard.
 *
 * Generated by:
 *   pac code add-data-source -a dataverse -t audit
 *   power-apps add-dataverse-api --api-name RetrieveAuditDetails
 *
 * If those generators are re-run with different shapes, update the SELECT_FIELDS
 * list and the mappers below.
 */

const OPERATION_BY_CODE: Record<number, AuditOperation> = {
  1: 'Create',
  2: 'Update',
  3: 'Delete',
  4: 'Access',
}

function initialsFrom(name: string): string {
  const parts = name.trim().split(/\s+/)
  const letters = (parts[0]?.[0] ?? '') + (parts[1]?.[0] ?? parts[0]?.[1] ?? '')
  return letters.toUpperCase() || '??'
}

const SELECT_FIELDS = [
  'auditid',
  'createdon',
  'operation',
  'objecttypecode',
  'objecttypecodename',
  '_objectid_value',
  'objectidname',
  '_userid_value',
  'useridname',
]

function toAuditEvent(row: Audits): AuditEvent {
  const opCode =
    typeof row.operation === 'number' ? row.operation : Number(row.operation)
  const userName = row.useridname ?? 'Unknown'
  const logical = row.objecttypecode ?? ''
  return {
    id: row.auditid,
    createdOn: row.createdon,
    operation: OPERATION_BY_CODE[opCode] ?? 'Update',
    tableName: row.objecttypecodename ?? logical,
    tableLogicalName: logical,
    recordId: row._objectid_value ?? '',
    recordName: row.objectidname ?? '',
    user: { name: userName, initials: initialsFrom(userName) },
    changes: [],
  }
}

/**
 * Defensive view of a RetrieveAuditDetails response. The function can return
 * an AttributeAuditDetail (the case we care about — column changes),
 * a ChangedAttributesAuditDetail, or a RelationshipAuditDetail. We map
 * OldValue / NewValue keys into a flat change list and ignore everything else.
 */
interface AttributeAuditDetail {
  OldValue?: Record<string, unknown>
  NewValue?: Record<string, unknown>
}
interface RetrieveAuditDetailsResponse {
  AuditDetail?: AttributeAuditDetail
}

function formatAuditValue(value: unknown): string {
  if (value === null || value === undefined) return ''
  if (typeof value === 'object') return JSON.stringify(value)
  return String(value)
}

function isAttributeKey(key: string): boolean {
  // Skip OData annotations (`@odata.type`, `attr@OData.Community...`) and the
  // implicit type discriminator. The remaining keys are attribute logical names.
  return !key.startsWith('@') && !key.includes('@odata.')
}

function mapAuditDetail(detail: AttributeAuditDetail | undefined): AttributeChange[] {
  if (!detail) return []
  const oldVals = detail.OldValue ?? {}
  const newVals = detail.NewValue ?? {}
  const keys = new Set<string>([
    ...Object.keys(oldVals).filter(isAttributeKey),
    ...Object.keys(newVals).filter(isAttributeKey),
  ])
  const changes: AttributeChange[] = []
  for (const key of keys) {
    changes.push({
      attribute: key,
      oldValue: formatAuditValue(oldVals[key]),
      newValue: formatAuditValue(newVals[key]),
    })
  }
  return changes
}

export class DataverseAuditService {
  async list(): Promise<AuditEvent[]> {
    try {
      const result = await AuditsService.getAll({
        select: SELECT_FIELDS,
        orderBy: ['createdon desc'],
        top: 500,
      })
      if (!result.success || !result.data) return mockAuditService.list()
      return result.data.map(toAuditEvent)
    } catch {
      return mockAuditService.list()
    }
  }

  async getChanges(auditId: string): Promise<AttributeChange[]> {
    try {
      const result =
        await RetrieveAuditDetailsService.RetrieveAuditDetails(auditId)
      if (!result.success || !result.data) {
        return mockAuditService.getChanges(auditId)
      }
      const response = result.data as RetrieveAuditDetailsResponse
      return mapAuditDetail(response.AuditDetail)
    } catch {
      return mockAuditService.getChanges(auditId)
    }
  }

  /**
   * Derive the slicer list from the distinct tables present in the audit log.
   *
   * The Power Apps code app data client only exposes per-table metadata
   * (`getEntityMetadata`) and Custom APIs — there is no direct OData query
   * against `EntityDefinitions`, so we can't filter on `IsAuditEnabled` from
   * here. Reading the log itself yields exactly the tables with activity in
   * the selected window, which is what the slicer shows anyway. Tables that
   * are audited but quiet won't appear until they have at least one event.
   */
  async listAuditedTables(): Promise<AuditedTable[]> {
    try {
      const result = await AuditsService.getAll({
        select: ['objecttypecode', 'objecttypecodename'],
        top: 5000,
      })
      if (!result.success || !result.data) {
        return mockAuditService.listAuditedTables()
      }
      const seen = new Map<string, AuditedTable>()
      for (const row of result.data) {
        const logical = row.objecttypecode
        if (!logical || seen.has(logical)) continue
        seen.set(logical, {
          logicalName: logical,
          displayName: row.objecttypecodename ?? logical,
        })
      }
      return [...seen.values()].sort((a, b) =>
        a.displayName.localeCompare(b.displayName),
      )
    } catch {
      return mockAuditService.listAuditedTables()
    }
  }
}

export const dataverseAuditService = new DataverseAuditService()
