import type {
  AttributeChange,
  AuditEvent,
  AuditOperation,
  AuditedTable,
} from '../types/audit'
import type { AuditListOptions, AuditListResult } from './auditService'
import { mockAuditService } from './mockAuditService'
import { powerModeReady } from '../PowerProvider'
import { AuditsService } from '../generated/services/AuditsService'
import { RetrieveAuditDetailsService } from '../generated/services/RetrieveAuditDetailsService'
import type { Audits } from '../generated/models/AuditsModel'

/**
 * Real implementation of {@link AuditService} backed by the Dataverse `audit`
 * table and the `RetrieveAuditDetails` function. It auto-falls back to the
 * mock service when running outside a Power Platform host, so local
 * `npm run dev` straight against Vite still produces a usable dashboard.
 *
 * Mode gating: every method awaits {@link powerModeReady} before touching the
 * generated client. Outside the host the SDK's connection lookup stalls
 * indefinitely instead of throwing, so a plain try/catch around the call
 * isn't enough — we have to short-circuit to mock when the provider has
 * resolved to `local-mock`.
 *
 * Generated by:
 *   pac code add-data-source -a dataverse -t audit
 *   power-apps add-dataverse-api --api-name RetrieveAuditDetails
 *
 * If those generators are re-run with different shapes, update the SELECT_FIELDS
 * list and the mappers below.
 */

const OPERATION_BY_CODE: Record<number, AuditOperation> = {
  1: 'Create',
  2: 'Update',
  3: 'Delete',
  4: 'Access',
}

function initialsFrom(name: string): string {
  const parts = name.trim().split(/\s+/)
  const letters = (parts[0]?.[0] ?? '') + (parts[1]?.[0] ?? parts[0]?.[1] ?? '')
  return letters.toUpperCase() || '??'
}

/**
 * Only real Web API columns may appear in `$select`. The `...name` properties
 * in the generated model (objecttypecodename, useridname, objectidname) are
 * SDK-side virtual attributes — selecting them yields 0x80060888 "Could not
 * find a property named ... on type Microsoft.Dynamics.CRM.audit". Their
 * display values arrive as OData formatted-value annotations instead.
 */
const SELECT_FIELDS = [
  'auditid',
  'createdon',
  'operation',
  'objecttypecode',
  '_objectid_value',
  '_userid_value',
]

/** OData annotation suffix carrying option-set / lookup display labels. */
const FV = '@OData.Community.Display.V1.FormattedValue'

/** Read the formatted-value annotation for a column, if present. */
function formatted(row: Record<string, unknown>, column: string): string | undefined {
  const value = row[`${column}${FV}`]
  return typeof value === 'string' && value !== '' ? value : undefined
}

function toAuditEvent(raw: Audits): AuditEvent {
  // Annotations aren't part of the generated model, so widen for access.
  const row = raw as Audits & Record<string, unknown>
  const opCode =
    typeof raw.operation === 'number' ? raw.operation : Number(raw.operation)
  const userName =
    formatted(row, '_userid_value') ?? raw.useridname ?? 'Unknown'
  const logical = raw.objecttypecode ?? ''
  return {
    id: raw.auditid,
    createdOn: raw.createdon,
    operation: OPERATION_BY_CODE[opCode] ?? 'Update',
    tableName:
      formatted(row, 'objecttypecode') ?? raw.objecttypecodename ?? logical,
    tableLogicalName: logical,
    recordId: raw._objectid_value ?? '',
    recordName:
      formatted(row, '_objectid_value') ?? raw.objectidname ?? '',
    user: { name: userName, initials: initialsFrom(userName) },
    changes: [],
  }
}

/**
 * Distinct tables present in a page of audit rows, sorted by display name.
 *
 * This is the slicer's only possible source here: the code app data client
 * exposes per-table metadata and Custom APIs, but no OData query against
 * `EntityDefinitions`, so `IsAuditEnabled` can't be filtered on. Tables that
 * are audited but quiet therefore stay hidden until they have an event.
 */
function toAuditedTables(rows: Audits[]): AuditedTable[] {
  const seen = new Map<string, AuditedTable>()
  for (const raw of rows) {
    const row = raw as Audits & Record<string, unknown>
    const logical = raw.objecttypecode
    if (!logical || seen.has(logical)) continue
    seen.set(logical, {
      logicalName: logical,
      displayName: formatted(row, 'objecttypecode') ?? logical,
    })
  }
  return [...seen.values()].sort((a, b) =>
    a.displayName.localeCompare(b.displayName),
  )
}

/**
 * Defensive view of a RetrieveAuditDetails response. The function can return
 * an AttributeAuditDetail (the case we care about — column changes),
 * a ChangedAttributesAuditDetail, or a RelationshipAuditDetail. We map
 * OldValue / NewValue keys into a flat change list and ignore everything else.
 */
interface AttributeAuditDetail {
  OldValue?: Record<string, unknown>
  NewValue?: Record<string, unknown>
}
interface RetrieveAuditDetailsResponse {
  AuditDetail?: AttributeAuditDetail
}

const GUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const ISO_DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/

/**
 * Best-effort display of a raw audit detail value. The SDK's custom-API
 * executor sends no `Prefer: odata.include-annotations` header (unlike
 * retrieveMultiple), so the RetrieveAuditDetails payload carries neither
 * lookup display names nor formatted dates — for lookups only the target
 * GUID is available. Until that's fixed upstream (or replaced by a
 * server-side custom API that resolves names), GUIDs are shortened and ISO
 * timestamps localized.
 */
function formatAuditValue(value: unknown): string {
  if (value === null || value === undefined) return ''
  if (typeof value === 'object') return JSON.stringify(value)
  const s = String(value)
  if (GUID_RE.test(s)) return `${s.slice(0, 8)}…${s.slice(-4)}`
  if (ISO_DATETIME_RE.test(s)) {
    const d = new Date(s)
    if (!Number.isNaN(d.getTime())) {
      return new Intl.DateTimeFormat('en-GB', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      }).format(d)
    }
  }
  return s
}

const FORMATTED_VALUE_RE = /@odata\.community\.display\.v1\.formattedvalue$/i

/**
 * Split a RetrieveAuditDetails entity payload into raw attribute values and
 * their formatted-value annotations. Lookups carry only a GUID in
 * `_x_value`; the display name (primary field of the target row) arrives as
 * `_x_value@OData.Community.Display.V1.FormattedValue` — same for option-set
 * labels and localized dates. All other annotation keys are dropped.
 */
function splitDetailEntity(entity: Record<string, unknown> | undefined): {
  values: Record<string, unknown>
  formatted: Record<string, string>
} {
  const values: Record<string, unknown> = {}
  const formatted: Record<string, string> = {}
  for (const [key, val] of Object.entries(entity ?? {})) {
    if (FORMATTED_VALUE_RE.test(key)) {
      formatted[key.replace(FORMATTED_VALUE_RE, '')] = String(val ?? '')
    } else if (!key.includes('@')) {
      values[key] = val
    }
  }
  return { values, formatted }
}

/** `_bookingstatus_value` → `bookingstatus`; other keys pass through. */
function attributeLabel(key: string): string {
  const lookup = key.match(/^_(.+)_value$/)
  return lookup ? lookup[1] : key
}

function mapAuditDetail(detail: AttributeAuditDetail | undefined): AttributeChange[] {
  if (!detail) return []
  const oldSide = splitDetailEntity(detail.OldValue)
  const newSide = splitDetailEntity(detail.NewValue)
  const keys = new Set<string>([
    ...Object.keys(oldSide.values),
    ...Object.keys(newSide.values),
  ])
  const changes: AttributeChange[] = []
  for (const key of keys) {
    changes.push({
      attribute: attributeLabel(key),
      oldValue: oldSide.formatted[key] ?? formatAuditValue(oldSide.values[key]),
      newValue: newSide.formatted[key] ?? formatAuditValue(newSide.values[key]),
    })
  }
  return changes
}

/**
 * Hard ceiling on how many audit rows the dashboard loads per query. The
 * connector runtime serves ~500 rows per page regardless of `top`, so every
 * 500 rows of cap cost one sequential round trip (skipToken paging) —
 * 25,000 means up to 50 requests on a large log. Raise with care.
 *
 * Hitting the cap is not a silent condition: {@link fetchAuditRows} reports it
 * and `list()` passes it up so the dashboard can mark its numbers incomplete.
 */
const ROW_CAP = 25_000

/**
 * Build the server-side `createdon` filter for a day window. Applying the
 * range in the query is what makes the range selector work at all: paging is
 * newest-first, so without it the cap fills with the most recent days no
 * matter which range is selected.
 */
function rangeFilter(sinceDays: number | undefined): string | undefined {
  if (sinceDays === undefined || !Number.isFinite(sinceDays)) return undefined
  const cutoff = new Date(Date.now() - sinceDays * 86_400_000).toISOString()
  return `createdon ge ${cutoff}`
}

/** Page of audit rows plus whether {@link ROW_CAP} cut the result short. */
interface AuditRowPage {
  /** Null only when the very first page failed — callers fall back to mock. */
  rows: Audits[] | null
  truncated: boolean
}

export class DataverseAuditService {
  /**
   * Fetch audit rows page by page until the result set is exhausted or
   * ROW_CAP is reached. Returns null when the first page already fails
   * (callers fall back to mock); later page failures return what we have.
   */
  private async fetchAuditRows(getAllOptions: {
    select: string[]
    orderBy?: string[]
    filter?: string
  }): Promise<AuditRowPage> {
    const rows: Audits[] = []
    let skipToken: string | undefined
    do {
      const result = await AuditsService.getAll({
        ...getAllOptions,
        ...(skipToken ? { skipToken } : {}),
      })
      if (!result.success || !result.data) {
        console.warn('[audit] page fetch failed — result:', result)
        // A failure mid-way leaves an incomplete set: report it as truncated
        // so partial data is never presented as a total.
        return { rows: rows.length ? rows : null, truncated: rows.length > 0 }
      }
      rows.push(...result.data)
      skipToken = result.skipToken
    } while (skipToken && rows.length < ROW_CAP)
    const truncated = Boolean(skipToken)
    if (truncated) {
      console.warn(
        `[audit] stopped paging at the ${ROW_CAP}-row cap — oldest events in range are truncated`,
      )
    }
    return { rows, truncated }
  }

  async list(options?: AuditListOptions): Promise<AuditListResult> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockAuditService.list(options)
    try {
      // Push the date range into the query — newest-first paging otherwise
      // returns the same most-recent slice regardless of the selected range.
      const filter = rangeFilter(options?.sinceDays)
      const { rows, truncated } = await this.fetchAuditRows({
        select: SELECT_FIELDS,
        orderBy: ['createdon desc'],
        ...(filter ? { filter } : {}),
      })
      if (!rows) {
        console.warn('[audit] list() falling back to mock')
        return mockAuditService.list(options)
      }
      console.info(
        '[audit] list() got',
        rows.length,
        'rows from Dataverse',
        filter ? `(filter: ${filter})` : '(no filter)',
        truncated ? '— TRUNCATED at the row cap' : '',
      )
      return {
        events: rows.map(toAuditEvent),
        tables: toAuditedTables(rows),
        truncated,
      }
    } catch (err) {
      console.warn('[audit] list() threw, falling back to mock:', err)
      return mockAuditService.list(options)
    }
  }

  async getChanges(auditId: string): Promise<AttributeChange[]> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockAuditService.getChanges(auditId)
    try {
      const result =
        await RetrieveAuditDetailsService.RetrieveAuditDetails(auditId)
      if (!result.success || !result.data) {
        console.warn(
          '[audit] getChanges() falling back to mock — result:',
          result,
        )
        return mockAuditService.getChanges(auditId)
      }
      const response = result.data as RetrieveAuditDetailsResponse
      // Diagnostic: shows whether the runtime delivers FormattedValue
      // annotations for lookups/option sets in the detail payload.
      console.debug('[audit] raw AuditDetail:', response.AuditDetail)
      return mapAuditDetail(response.AuditDetail)
    } catch (err) {
      console.warn('[audit] getChanges() threw, falling back to mock:', err)
      return mockAuditService.getChanges(auditId)
    }
  }
}

export const dataverseAuditService = new DataverseAuditService()
