import type {
  CreateWorkingSolutionInput,
  MergeResult,
  PublisherInfo,
  SolutionComponentInfo,
  WorkItemInfo,
  WorkingSolution,
} from '../types/solution'
import type { SolutionService } from './solutionService'
import { mockSolutionService } from './mockSolutionService'
import { powerModeReady } from '../PowerProvider'
import {
  buildUniqueName,
  classifyUniqueName,
  extractDevOpsId,
} from '../utils/naming'
import { shortGuid } from '../utils/format'
import { ADO_ACCOUNT, ADO_PROJECT_NAME, devOpsWorkItemUrl } from '../config'
import { SolutionsService } from '../generated/services/SolutionsService'
import { PublishersService } from '../generated/services/PublishersService'
import { SolutioncomponentsService } from '../generated/services/SolutioncomponentsService'
import { Msdyn_solutioncomponentsummariesService } from '../generated/services/Msdyn_solutioncomponentsummariesService'
import type { Msdyn_solutioncomponentsummaries } from '../generated/models/Msdyn_solutioncomponentsummariesModel'
import { AddSolutionComponentService } from '../generated/services/AddSolutionComponentService'
import { AzureDevOpsService } from '../generated/services/AzureDevOpsService'
import type { Solutions, SolutionsBase } from '../generated/models/SolutionsModel'
import type { Solutioncomponents } from '../generated/models/SolutioncomponentsModel'
import type { Publishers } from '../generated/models/PublishersModel'
import type { IGetAllOptions } from '../generated/models/CommonModels'
import type { IOperationResult } from '@microsoft/power-apps/data'

/**
 * Real implementation of {@link SolutionService} backed by the Dataverse
 * `solution`, `publisher` and `solutioncomponent` tables plus the
 * `AddSolutionComponent` action (merge). It auto-falls back to the mock
 * service when running outside a Power Platform host, so plain
 * `npm run dev` straight against Vite still produces a usable app.
 *
 * Mode gating: every method awaits {@link powerModeReady} before touching the
 * generated client. Outside the host the SDK's connection lookup stalls
 * indefinitely instead of throwing, so a plain try/catch around the call
 * isn't enough — we short-circuit to mock when the provider has resolved to
 * `local-mock`.
 *
 * Generated by:
 *   pac code add-data-source -a dataverse -t solution
 *   pac code add-data-source -a dataverse -t publisher
 *   pac code add-data-source -a dataverse -t solutioncomponent
 *   pac code add-data-source -a dataverse -t msdyn_solutioncomponentsummary
 *   power-apps add-dataverse-api  (AddSolutionComponent)
 *
 * If those generators are re-run with different shapes, update the SELECT
 * lists and the mappers below.
 */

/** OData annotation suffix carrying option-set / lookup display labels. */
const FV = '@OData.Community.Display.V1.FormattedValue'

/** Read the formatted-value annotation for a column, if present. */
function formatted(row: Record<string, unknown>, column: string): string | undefined {
  const value = row[`${column}${FV}`]
  return typeof value === 'string' && value !== '' ? value : undefined
}

/**
 * English fallback labels for `componenttype` codes. The runtime's
 * formatted-value annotation wins when present (locale-aware — this
 * environment delivers German labels); unknown codes render as "Type <code>".
 */
const COMPONENT_TYPE_LABELS: Record<number, string> = {
  1: 'Table',
  2: 'Column',
  3: 'Relationship',
  9: 'Choice',
  10: 'Table Relationship',
  20: 'Security Role',
  24: 'Form',
  26: 'View',
  29: 'Process',
  31: 'Report',
  36: 'Email Template',
  44: 'Duplicate Rule',
  59: 'Chart',
  60: 'Form',
  61: 'Web Resource',
  62: 'Site Map',
  63: 'Connection Role',
  66: 'Custom Control',
  70: 'Field Security Profile',
  80: 'Model-driven App',
  91: 'Plugin Assembly',
  92: 'SDK Message Step',
  93: 'SDK Message Step Image',
  95: 'Service Endpoint',
  150: 'Routing Rule',
  300: 'Canvas App',
  371: 'Connector',
  372: 'Connection Reference',
  380: 'Environment Variable',
  381: 'Environment Variable Value',
}

/**
 * Only real Web API columns may appear in `$select`. The `...name` properties
 * in the generated models (publisheridname, componenttypename, …) are
 * SDK-side virtual attributes — selecting them yields 0x80060888. Their
 * display values arrive as OData formatted-value annotations instead.
 */
const SOLUTION_SELECT = [
  'solutionid',
  'uniquename',
  'friendlyname',
  'description',
  'version',
  'ismanaged',
  'createdon',
  'modifiedon',
  '_publisherid_value',
]

function toWorkingSolution(raw: Solutions): WorkingSolution {
  // Annotations aren't part of the generated model, so widen for access.
  const row = raw as Solutions & Record<string, unknown>
  const uniqueName = raw.uniquename
  const title = raw.friendlyname || uniqueName
  const { kind } = classifyUniqueName(uniqueName)
  // Falls back to numbers carried in the title ("Assembly App V2 | 11941")
  // or a numeric unique name, so pre-convention solutions also link to
  // their DevOps work item.
  const devOpsId = extractDevOpsId(uniqueName, title)
  const publisherId = raw._publisherid_value ?? ''
  return {
    id: raw.solutionid,
    uniqueName,
    title,
    description: raw.description ?? '',
    kind,
    devOpsId,
    version: raw.version,
    isManaged: raw.ismanaged === true,
    createdOn: raw.createdon ?? '',
    modifiedOn: raw.modifiedon ?? '',
    publisher: publisherId
      ? {
          id: publisherId,
          uniqueName: '',
          friendlyName:
            formatted(row, '_publisherid_value') ?? raw.publisheridname ?? '',
          prefix: raw.publisheridprefix ?? '',
        }
      : null,
  }
}

/**
 * Map one row of the `msdyn_solutioncomponentsummary` virtual table — the
 * same source the maker portal uses for the solution objects list, so it
 * carries resolved display names. Subcomponent rows (columns, forms, …)
 * additionally name their owning table in msdyn_primaryentityname.
 */
function summaryToComponentInfo(
  raw: Msdyn_solutioncomponentsummaries,
  behaviorByObjectId: Map<string, number>,
): SolutionComponentInfo {
  const typeCode = Number(raw.msdyn_componenttype ?? 0)
  const typeName =
    raw.msdyn_componenttypename ??
    COMPONENT_TYPE_LABELS[typeCode] ??
    `Type ${typeCode}`
  const objectId = raw.msdyn_objectid ?? ''
  const displayName =
    raw.msdyn_displayname || raw.msdyn_name || `${typeName} ${shortGuid(objectId)}`
  const rootBehavior = behaviorByObjectId.get(objectId)
  return {
    id: raw.msdyn_solutioncomponentsummaryid,
    objectId,
    typeCode,
    typeName,
    displayName,
    ...(raw.msdyn_schemaname ? { schemaName: raw.msdyn_schemaname } : {}),
    ...(raw.msdyn_primaryentityname
      ? { parentTable: raw.msdyn_primaryentityname }
      : {}),
    ...(rootBehavior !== undefined ? { rootBehavior } : {}),
  }
}

function toComponentInfo(raw: Solutioncomponents): SolutionComponentInfo {
  const row = raw as Solutioncomponents & Record<string, unknown>
  const typeCode = Number(raw.componenttype ?? 0)
  const typeName =
    formatted(row, 'componenttype') ??
    COMPONENT_TYPE_LABELS[typeCode] ??
    `Type ${typeCode}`
  const objectId = raw.objectid ?? ''
  const rootBehavior =
    raw.rootcomponentbehavior !== undefined
      ? Number(raw.rootcomponentbehavior)
      : undefined
  return {
    id: raw.solutioncomponentid,
    objectId,
    typeCode,
    typeName,
    // The base table doesn't carry display names; the maker portal resolves
    // them via msdyn_solutioncomponentsummary. Until that richer source is
    // wired, show the type plus a shortened object id.
    displayName: `${typeName} ${shortGuid(objectId)}`,
    ...(rootBehavior !== undefined ? { rootBehavior } : {}),
  }
}

/** Page through a generated getAll until the result set is exhausted. */
async function fetchAll<T>(
  getAll: (options?: IGetAllOptions) => Promise<IOperationResult<T[]>>,
  options: IGetAllOptions,
): Promise<T[] | null> {
  const rows: T[] = []
  let skipToken: string | undefined
  do {
    const result = await getAll({
      ...options,
      ...(skipToken ? { skipToken } : {}),
    })
    if (!result.success || !result.data) {
      console.warn('[solutions] page fetch failed — result:', result)
      return rows.length ? rows : null
    }
    rows.push(...result.data)
    skipToken = result.skipToken
  } while (skipToken)
  return rows
}

export class DataverseSolutionService implements SolutionService {
  async listSolutions(): Promise<WorkingSolution[]> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockSolutionService.listSolutions()
    try {
      const rows = await fetchAll(
        (o) => SolutionsService.getAll(o),
        {
          select: SOLUTION_SELECT,
          // Working solutions are always unmanaged; isvisible drops the
          // hidden system containers (Active, Basic, …).
          filter: 'ismanaged eq false and isvisible eq true',
          orderBy: ['modifiedon desc'],
        },
      )
      if (!rows) return mockSolutionService.listSolutions()
      return rows
        .map(toWorkingSolution)
        .filter((s) => s.uniqueName.toLowerCase() !== 'default')
    } catch (err) {
      console.warn('[solutions] listSolutions() threw, falling back to mock:', err)
      return mockSolutionService.listSolutions()
    }
  }

  async listPublishers(): Promise<PublisherInfo[]> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockSolutionService.listPublishers()
    try {
      const rows = await fetchAll(
        (o) => PublishersService.getAll(o),
        {
          select: [
            'publisherid',
            'uniquename',
            'friendlyname',
            'customizationprefix',
          ],
          filter: 'isreadonly eq false',
          orderBy: ['friendlyname asc'],
        },
      )
      if (!rows) return mockSolutionService.listPublishers()
      return rows.map((row: Publishers) => ({
        id: row.publisherid,
        uniqueName: row.uniquename,
        friendlyName: row.friendlyname ?? row.uniquename,
        prefix: row.customizationprefix ?? '',
      }))
    } catch (err) {
      console.warn('[solutions] listPublishers() threw, falling back to mock:', err)
      return mockSolutionService.listPublishers()
    }
  }

  async createWorkingSolution(
    input: CreateWorkingSolutionInput,
  ): Promise<WorkingSolution> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.createWorkingSolution(input)
    const uniqueName = buildUniqueName(input.kind, input.devOpsId)
    // The generated Base type also lists server-managed columns
    // (sourcecontrolsyncstatus, enabledforsourcecontrolintegration) as
    // required — Dataverse rejects writes to them, so send the minimal
    // create payload and cast. The bind key must be the EDM navigation
    // property `publisherid` (lowercase); the generated model's
    // "PublisherId@odata.bind" spelling is rejected with 0x80048d19
    // "undeclared property 'PublisherId'".
    const record = {
      uniquename: uniqueName,
      friendlyname: input.title,
      description: input.description,
      version: '1.0.0.0',
      'publisherid@odata.bind': `/publishers(${input.publisherId})`,
    } as unknown as Omit<SolutionsBase, 'solutionid'>
    const result = await SolutionsService.create(record)
    if (!result.success || !result.data) {
      console.warn('[solutions] create failed — result:', result)
      throw new Error(
        `Dataverse rejected the solution "${uniqueName}" — it may already exist ` +
          'or the publisher is invalid.',
      )
    }
    return toWorkingSolution(result.data)
  }

  /** Raw `solutioncomponent` rows — root components plus their behaviors. */
  private async fetchRawComponents(
    solutionId: string,
  ): Promise<Solutioncomponents[] | null> {
    return fetchAll(
      (o) => SolutioncomponentsService.getAll(o),
      {
        select: [
          'solutioncomponentid',
          'componenttype',
          'objectid',
          'rootcomponentbehavior',
        ],
        filter: `_solutionid_value eq ${solutionId}`,
      },
    )
  }

  async listComponents(solutionId: string): Promise<SolutionComponentInfo[]> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.listComponents(solutionId)
    try {
      // The summary virtual table resolves display names (it's what the
      // maker portal renders); the raw table supplies rootcomponentbehavior,
      // which the merge needs. Join the two on objectid.
      const [summaryRows, rawRows] = await Promise.all([
        fetchAll(
          (o) => Msdyn_solutioncomponentsummariesService.getAll(o),
          {
            select: [
              'msdyn_solutioncomponentsummaryid',
              'msdyn_objectid',
              'msdyn_componenttype',
              'msdyn_componenttypename',
              'msdyn_displayname',
              'msdyn_name',
              'msdyn_schemaname',
              'msdyn_primaryentityname',
            ],
            filter: `msdyn_solutionid eq '${solutionId}'`,
          },
        ).catch((err) => {
          console.warn('[solutions] summary query threw:', err)
          return null
        }),
        this.fetchRawComponents(solutionId),
      ])

      const behaviorByObjectId = new Map<string, number>()
      for (const row of rawRows ?? []) {
        if (row.objectid && row.rootcomponentbehavior !== undefined)
          behaviorByObjectId.set(row.objectid, Number(row.rootcomponentbehavior))
      }

      const mapped = summaryRows?.length
        ? summaryRows.map((r) => summaryToComponentInfo(r, behaviorByObjectId))
        : (rawRows ?? []).map(toComponentInfo)
      if (!summaryRows?.length && !rawRows)
        return mockSolutionService.listComponents(solutionId)
      return mapped.sort(
        (a, b) =>
          a.typeName.localeCompare(b.typeName) ||
          a.displayName.localeCompare(b.displayName),
      )
    } catch (err) {
      console.warn('[solutions] listComponents() threw, falling back to mock:', err)
      return mockSolutionService.listComponents(solutionId)
    }
  }

  /**
   * Work item summary via the Azure DevOps connector
   * (`pac code add-data-source -a shared_visualstudioteamservices -c <id>`).
   * `ListWorkItems` is used instead of `GetWorkItemDetails` because the
   * latter requires the work item type, which we don't know up front.
   * Org ("account") and project come from VITE_ADO_ORG_URL / VITE_ADO_PROJECT.
   */
  async getWorkItem(devOpsId: string): Promise<WorkItemInfo | null> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockSolutionService.getWorkItem(devOpsId)
    if (!ADO_ACCOUNT || !ADO_PROJECT_NAME) {
      console.info('[devops] VITE_ADO_ORG_URL / VITE_ADO_PROJECT not set')
      return null
    }
    try {
      const result = await AzureDevOpsService.ListWorkItems(
        ADO_ACCOUNT,
        ADO_PROJECT_NAME,
        devOpsId,
      )
      if (!result.success || !result.data) {
        console.warn('[devops] ListWorkItems failed — result:', result)
        return null
      }
      const item = result.data.value?.find(
        (wi) => String(wi.System_Id ?? '') === devOpsId,
      )
      if (!item) return null
      return {
        id: devOpsId,
        type: item.System_WorkItemType ?? 'Work Item',
        title: item.System_Title ?? '',
        state: item.System_State ?? 'Unknown',
        assignedTo: item.System_AssignedTo || null,
        url: devOpsWorkItemUrl(devOpsId),
      }
    } catch (err) {
      console.warn('[devops] getWorkItem() threw:', err)
      return null
    }
  }

  async mergeIntoDeployment(
    targetUniqueName: string,
    sourceSolutionIds: string[],
    onProgress?: (done: number, total: number) => void,
  ): Promise<MergeResult> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.mergeIntoDeployment(
        targetUniqueName,
        sourceSolutionIds,
        onProgress,
      )

    // Resolve target id + the components already present, so re-merges skip
    // instead of failing.
    const solutions = await this.listSolutions()
    const target = solutions.find((s) => s.uniqueName === targetUniqueName)
    if (!target) throw new Error(`Unknown target solution ${targetUniqueName}`)
    const existing = new Set(
      (await this.listComponents(target.id)).map((c) => c.objectId),
    )

    const queue: SolutionComponentInfo[] = []
    for (const id of sourceSolutionIds) {
      queue.push(...(await this.listComponents(id)))
    }

    const result: MergeResult = { added: 0, skipped: 0, errors: [] }
    let done = 0
    for (const component of queue) {
      if (existing.has(component.objectId)) {
        result.skipped++
      } else {
        try {
          // Carry the source's subcomponent behavior over to the target:
          // 0 = include subcomponents, 1 = do not include, 2 = shell only
          // (signalled by an empty IncludedComponentSettingsValues).
          const doNotIncludeSubcomponents =
            component.rootBehavior === 1 || component.rootBehavior === 2
          const res = await AddSolutionComponentService.AddSolutionComponent(
            component.objectId,
            component.typeCode,
            targetUniqueName,
            false,
            doNotIncludeSubcomponents,
            component.rootBehavior === 2 ? [] : undefined,
          )
          if (res.success) {
            existing.add(component.objectId)
            result.added++
          } else {
            console.warn('[solutions] AddSolutionComponent failed:', res)
            result.errors.push(
              `${component.typeName} ${shortGuid(component.objectId)}: rejected`,
            )
          }
        } catch (err) {
          result.errors.push(
            `${component.typeName} ${shortGuid(component.objectId)}: ${String(err)}`,
          )
        }
      }
      onProgress?.(++done, queue.length)
    }
    return result
  }
}

export const dataverseSolutionService = new DataverseSolutionService()
