import type {
  CreateWorkingSolutionInput,
  MergeResult,
  PublisherInfo,
  SolutionComponentInfo,
  SolutionKind,
  TrackSolutionInput,
  WorkItemInfo,
  WorkingSolution,
} from '../types/solution'
import type { SolutionService } from './solutionService'
import { mockSolutionService } from './mockSolutionService'
import { hostUserHints, powerModeReady } from '../PowerProvider'
import {
  buildUniqueName,
  classifyUniqueName,
  extractDevOpsId,
} from '../utils/naming'
import { shortGuid } from '../utils/format'
import { DEVOPS_PANEL_ENABLED, makerSolutionUrl } from '../config'
import { SolutionsService } from '../generated/services/SolutionsService'
import { PublishersService } from '../generated/services/PublishersService'
import { SolutioncomponentsService } from '../generated/services/SolutioncomponentsService'
import { Msdyn_solutioncomponentsummariesService } from '../generated/services/Msdyn_solutioncomponentsummariesService'
import type { Msdyn_solutioncomponentsummaries } from '../generated/models/Msdyn_solutioncomponentsummariesModel'
import { AddSolutionComponentService } from '../generated/services/AddSolutionComponentService'
import { Ssid_workingsolutionsService } from '../generated/services/Ssid_workingsolutionsService'
import type {
  Ssid_workingsolutions,
  Ssid_workingsolutionsBase,
} from '../generated/models/Ssid_workingsolutionsModel'
import { MicrosoftDataverseService } from '../generated/services/MicrosoftDataverseService'
import { SystemusersService } from '../generated/services/SystemusersService'
import type { Solutions, SolutionsBase } from '../generated/models/SolutionsModel'
import type { Solutioncomponents } from '../generated/models/SolutioncomponentsModel'
import type { Publishers } from '../generated/models/PublishersModel'
import type { IGetAllOptions } from '../generated/models/CommonModels'
import type { IOperationResult } from '@microsoft/power-apps/data'

/**
 * Real implementation of {@link SolutionService} backed by the Dataverse
 * `solution`, `publisher` and `solutioncomponent` tables plus the
 * `AddSolutionComponent` action (merge). It auto-falls back to the mock
 * service when running outside a Power Platform host, so plain
 * `npm run dev` straight against Vite still produces a usable app.
 *
 * Mode gating: every method awaits {@link powerModeReady} before touching the
 * generated client. Outside the host the SDK's connection lookup stalls
 * indefinitely instead of throwing, so a plain try/catch around the call
 * isn't enough — we short-circuit to mock when the provider has resolved to
 * `local-mock`.
 *
 * Generated by:
 *   pac code add-data-source -a dataverse -t solution
 *   pac code add-data-source -a dataverse -t publisher
 *   pac code add-data-source -a dataverse -t solutioncomponent
 *   pac code add-data-source -a dataverse -t msdyn_solutioncomponentsummary
 *   power-apps add-dataverse-api  (AddSolutionComponent)
 *
 * If those generators are re-run with different shapes, update the SELECT
 * lists and the mappers below.
 */

/** OData annotation suffix carrying option-set / lookup display labels. */
const FV = '@OData.Community.Display.V1.FormattedValue'

/** Read the formatted-value annotation for a column, if present. */
function formatted(row: Record<string, unknown>, column: string): string | undefined {
  const value = row[`${column}${FV}`]
  return typeof value === 'string' && value !== '' ? value : undefined
}

/**
 * English fallback labels for `componenttype` codes. The runtime's
 * formatted-value annotation wins when present (locale-aware — this
 * environment delivers German labels); unknown codes render as "Type <code>".
 */
const COMPONENT_TYPE_LABELS: Record<number, string> = {
  1: 'Table',
  2: 'Column',
  3: 'Relationship',
  9: 'Choice',
  10: 'Table Relationship',
  20: 'Security Role',
  24: 'Form',
  26: 'View',
  29: 'Process',
  31: 'Report',
  36: 'Email Template',
  44: 'Duplicate Rule',
  59: 'Chart',
  60: 'Form',
  61: 'Web Resource',
  62: 'Site Map',
  63: 'Connection Role',
  66: 'Custom Control',
  70: 'Field Security Profile',
  80: 'Model-driven App',
  91: 'Plugin Assembly',
  92: 'SDK Message Step',
  93: 'SDK Message Step Image',
  95: 'Service Endpoint',
  150: 'Routing Rule',
  300: 'Canvas App',
  371: 'Connector',
  372: 'Connection Reference',
  380: 'Environment Variable',
  381: 'Environment Variable Value',
}

/**
 * Only real Web API columns may appear in `$select`. The `...name` properties
 * in the generated models (publisheridname, componenttypename, …) are
 * SDK-side virtual attributes — selecting them yields 0x80060888. Their
 * display values arrive as OData formatted-value annotations instead.
 */
/**
 * ssid_workingsolution presentation layer: sst_type_opt choice values ↔
 * SolutionKind (the internal key for Release stays 'deployment').
 */
const KIND_BY_TYPE_OPT: Record<number, SolutionKind> = {
  867520000: 'feature',
  867520001: 'bug',
  867520002: 'deployment',
}
const TYPE_OPT_BY_KIND: Record<CreateWorkingSolutionInput['kind'], number> = {
  feature: 867520000,
  bug: 867520001,
  deployment: 867520002,
}
/** ssid_deploymentstatus: initial value and the "merged" log state. */
const DEPLOYMENT_STATUS_NONE = 500870000
const DEPLOYMENT_STATUS_MERGED = 867520001

const WORKING_ROW_SELECT = [
  'ssid_workingsolutionid',
  'ssid_name',
  'ssid_devopsid',
  'ssid_uniquesolutionname',
  'sst_type_opt',
  'sst_devopsworkitemtype',
  'ssid_deploymentstatus',
  '_ownerid_value',
  'createdon',
  'modifiedon',
]

/**
 * Derive the kind from the synced DevOps work item type whenever
 * sst_type_opt is not set explicitly:
 *   Bug → Bug; Change Request / Feature / Product Backlog Item → Feature.
 */
function kindFromWorkItemType(workItemType?: string): SolutionKind | undefined {
  const t = (workItemType ?? '').toLowerCase()
  if (!t) return undefined
  if (t.includes('bug')) return 'bug'
  if (
    t.includes('change request') ||
    t === 'cr' ||
    t.includes('feature') ||
    t.includes('backlog')
  )
    return 'feature'
  return undefined
}

/**
 * Some component types arrive as untranslated resource keys like
 * "Customization.Type_SecurityRole" — strip the prefix and space out the
 * PascalCase tail ("Security Role", "Plugin Assembly", …).
 */
function prettifyTypeName(name: string): string {
  const match = /^Customization\.Type_(.+)$/.exec(name)
  if (!match) return name
  return match[1]
    .replace(/_/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replace(/\bSdk\b/g, 'SDK')
    .trim()
}

const SOLUTION_SELECT = [
  'solutionid',
  'uniquename',
  'friendlyname',
  'description',
  'version',
  'ismanaged',
  'createdon',
  'modifiedon',
  '_publisherid_value',
]

function toWorkingSolution(raw: Solutions): WorkingSolution {
  // Annotations aren't part of the generated model, so widen for access.
  const row = raw as Solutions & Record<string, unknown>
  const uniqueName = raw.uniquename
  const title = raw.friendlyname || uniqueName
  const { kind } = classifyUniqueName(uniqueName)
  // Falls back to numbers carried in the title ("Assembly App V2 | 11941")
  // or a numeric unique name, so pre-convention solutions also link to
  // their DevOps work item.
  const devOpsId = extractDevOpsId(uniqueName, title)
  const publisherId = raw._publisherid_value ?? ''
  return {
    id: raw.solutionid,
    uniqueName,
    title,
    description: raw.description ?? '',
    kind,
    devOpsId,
    version: raw.version,
    isManaged: raw.ismanaged === true,
    createdOn: raw.createdon ?? '',
    modifiedOn: raw.modifiedon ?? '',
    publisher: publisherId
      ? {
          id: publisherId,
          uniqueName: '',
          friendlyName:
            formatted(row, '_publisherid_value') ?? raw.publisheridname ?? '',
          prefix: raw.publisheridprefix ?? '',
        }
      : null,
  }
}

/**
 * Map one row of the `msdyn_solutioncomponentsummary` virtual table — the
 * same source the maker portal uses for the solution objects list, so it
 * carries resolved display names. Subcomponent rows (columns, forms, …)
 * additionally name their owning table in msdyn_primaryentityname.
 */
function summaryToComponentInfo(
  raw: Msdyn_solutioncomponentsummaries,
  behaviorByObjectId: Map<string, number>,
): SolutionComponentInfo {
  const typeCode = Number(raw.msdyn_componenttype ?? 0)
  const typeName = prettifyTypeName(
    raw.msdyn_componenttypename ??
      COMPONENT_TYPE_LABELS[typeCode] ??
      `Type ${typeCode}`,
  )
  const objectId = raw.msdyn_objectid ?? ''
  const displayName =
    raw.msdyn_displayname || raw.msdyn_name || `${typeName} ${shortGuid(objectId)}`
  const rootBehavior = behaviorByObjectId.get(objectId)
  return {
    id: raw.msdyn_solutioncomponentsummaryid,
    objectId,
    typeCode,
    typeName,
    displayName,
    ...(raw.msdyn_schemaname ? { schemaName: raw.msdyn_schemaname } : {}),
    ...(raw.msdyn_primaryentityname
      ? { parentTable: raw.msdyn_primaryentityname }
      : {}),
    ...(rootBehavior !== undefined ? { rootBehavior } : {}),
  }
}

function toComponentInfo(raw: Solutioncomponents): SolutionComponentInfo {
  const row = raw as Solutioncomponents & Record<string, unknown>
  const typeCode = Number(raw.componenttype ?? 0)
  const typeName = prettifyTypeName(
    formatted(row, 'componenttype') ??
      COMPONENT_TYPE_LABELS[typeCode] ??
      `Type ${typeCode}`,
  )
  const objectId = raw.objectid ?? ''
  const rootBehavior =
    raw.rootcomponentbehavior !== undefined
      ? Number(raw.rootcomponentbehavior)
      : undefined
  return {
    id: raw.solutioncomponentid,
    objectId,
    typeCode,
    typeName,
    // The base table doesn't carry display names; the maker portal resolves
    // them via msdyn_solutioncomponentsummary. Until that richer source is
    // wired, show the type plus a shortened object id.
    displayName: `${typeName} ${shortGuid(objectId)}`,
    ...(rootBehavior !== undefined ? { rootBehavior } : {}),
  }
}

/** Page through a generated getAll until the result set is exhausted. */
async function fetchAll<T>(
  getAll: (options?: IGetAllOptions) => Promise<IOperationResult<T[]>>,
  options: IGetAllOptions,
): Promise<T[] | null> {
  const rows: T[] = []
  let skipToken: string | undefined
  do {
    const result = await getAll({
      ...options,
      ...(skipToken ? { skipToken } : {}),
    })
    if (!result.success || !result.data) {
      console.warn('[solutions] page fetch failed — result:', result)
      return rows.length ? rows : null
    }
    rows.push(...result.data)
    skipToken = result.skipToken
  } while (skipToken)
  return rows
}

export class DataverseSolutionService implements SolutionService {
  /** Active rows of the ssid_workingsolution presentation table. */
  private async fetchWorkingRows(): Promise<Ssid_workingsolutions[]> {
    const rows = await fetchAll(
      (o) => Ssid_workingsolutionsService.getAll(o),
      {
        select: WORKING_ROW_SELECT,
        filter: 'statecode eq 0',
      },
    )
    return rows ?? []
  }

  /**
   * The workbench list: ssid_workingsolution rows (curated layer — title,
   * DevOps id, type, owner, deployment status) enriched with the linked
   * real solution (version, publisher, dates), joined on
   * ssid_uniquesolutionname. Real unmanaged solutions without a row keep
   * showing up, classified by the unique-name convention (mostly "Other").
   */
  async listSolutions(): Promise<WorkingSolution[]> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockSolutionService.listSolutions()
    try {
      const [rows, workingRows] = await Promise.all([
        fetchAll((o) => SolutionsService.getAll(o), {
          select: SOLUTION_SELECT,
          // Working solutions are always unmanaged; isvisible drops the
          // hidden system containers (Active, Basic, …).
          filter: 'ismanaged eq false and isvisible eq true',
          orderBy: ['modifiedon desc'],
        }),
        this.fetchWorkingRows().catch((err) => {
          console.warn('[solutions] working-solution rows failed:', err)
          return [] as Ssid_workingsolutions[]
        }),
      ])
      if (!rows) return mockSolutionService.listSolutions()
      const solutions = rows
        .map(toWorkingSolution)
        .filter((s) => s.uniqueName.toLowerCase() !== 'default')
      const byUniqueName = new Map(
        solutions.map((s) => [s.uniqueName.toLowerCase(), s]),
      )

      const result: WorkingSolution[] = []
      const linkedSolutionIds = new Set<string>()
      for (const raw of workingRows) {
        const row = raw as Ssid_workingsolutions & Record<string, unknown>
        const uniqueName = raw.ssid_uniquesolutionname ?? ''
        const solution = uniqueName
          ? byUniqueName.get(uniqueName.toLowerCase())
          : undefined
        if (solution) linkedSolutionIds.add(solution.id)
        const kind =
          KIND_BY_TYPE_OPT[Number(raw.sst_type_opt ?? -1)] ??
          kindFromWorkItemType(raw.sst_devopsworkitemtype) ??
          solution?.kind ??
          classifyUniqueName(uniqueName).kind
        result.push({
          id: solution?.id ?? `missing-${raw.ssid_workingsolutionid}`,
          recordId: raw.ssid_workingsolutionid,
          uniqueName: solution?.uniqueName ?? uniqueName,
          title: raw.ssid_name || (solution?.title ?? uniqueName),
          description: solution?.description ?? '',
          kind,
          devOpsId: raw.ssid_devopsid || solution?.devOpsId || null,
          version: solution?.version ?? '',
          isManaged: solution?.isManaged ?? false,
          createdOn: solution?.createdOn ?? raw.createdon ?? '',
          modifiedOn: solution?.modifiedOn ?? raw.modifiedon ?? '',
          publisher: solution?.publisher ?? null,
          owner: formatted(row, '_ownerid_value') ?? raw.owneridname,
          ownerId:
            typeof row._ownerid_value === 'string'
              ? row._ownerid_value
              : undefined,
          deploymentStatus:
            formatted(row, 'ssid_deploymentstatus') ??
            raw.ssid_deploymentstatusname,
          ...(solution ? {} : { solutionMissing: true as const }),
        })
      }
      // Solutions that have no presentation row yet.
      for (const solution of solutions) {
        if (!linkedSolutionIds.has(solution.id)) result.push(solution)
      }
      return result.sort((a, b) => b.modifiedOn.localeCompare(a.modifiedOn))
    } catch (err) {
      console.warn('[solutions] listSolutions() threw, falling back to mock:', err)
      return mockSolutionService.listSolutions()
    }
  }

  async listPublishers(): Promise<PublisherInfo[]> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockSolutionService.listPublishers()
    try {
      const rows = await fetchAll(
        (o) => PublishersService.getAll(o),
        {
          select: [
            'publisherid',
            'uniquename',
            'friendlyname',
            'customizationprefix',
          ],
          filter: 'isreadonly eq false',
          orderBy: ['friendlyname asc'],
        },
      )
      if (!rows) return mockSolutionService.listPublishers()
      return rows.map((row: Publishers) => ({
        id: row.publisherid,
        uniqueName: row.uniquename,
        friendlyName: row.friendlyname ?? row.uniquename,
        prefix: row.customizationprefix ?? '',
      }))
    } catch (err) {
      console.warn('[solutions] listPublishers() threw, falling back to mock:', err)
      return mockSolutionService.listPublishers()
    }
  }

  /**
   * The ssid_workingsolution table requires a ssid_WorkbenchSetting lookup;
   * resolve the first available settings row via the Dataverse connector
   * (no dedicated typed data source needed for a single id).
   */
  private async defaultWorkbenchSettingId(): Promise<string | null> {
    try {
      const result = await MicrosoftDataverseService.ListRecords(
        'ssid_workbenchsettings',
        undefined,
        undefined,
        undefined,
        'ssid_workbenchsettingid',
        undefined,
        undefined,
        undefined,
        undefined,
        1,
      )
      const rows =
        (result.data as { value?: Record<string, unknown>[] } | undefined)
          ?.value ?? []
      const id = rows[0]?.ssid_workbenchsettingid
      return typeof id === 'string' && id ? id : null
    } catch (err) {
      console.warn('[solutions] workbench setting lookup failed:', err)
      return null
    }
  }

  async createWorkingSolution(
    input: CreateWorkingSolutionInput,
  ): Promise<WorkingSolution> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.createWorkingSolution(input)
    const uniqueName = buildUniqueName(input.kind, input.devOpsId)
    // The generated Base type also lists server-managed columns
    // (sourcecontrolsyncstatus, enabledforsourcecontrolintegration) as
    // required — Dataverse rejects writes to them, so send the minimal
    // create payload and cast. The bind key must be the EDM navigation
    // property `publisherid` (lowercase); the generated model's
    // "PublisherId@odata.bind" spelling is rejected with 0x80048d19
    // "undeclared property 'PublisherId'".
    const record = {
      uniquename: uniqueName,
      friendlyname: input.title,
      description: input.description,
      version: '1.0.0.0',
      'publisherid@odata.bind': `/publishers(${input.publisherId})`,
    } as unknown as Omit<SolutionsBase, 'solutionid'>
    const result = await SolutionsService.create(record)
    if (!result.success || !result.data) {
      console.warn('[solutions] create failed — result:', result)
      throw new Error(
        `Dataverse rejected the solution "${uniqueName}" — it may already exist ` +
          'or the publisher is invalid.',
      )
    }
    const solution = toWorkingSolution(result.data)

    // Presentation layer: the ssid_workingsolution row carrying title,
    // DevOps id, type and the link back to the real solution.
    let recordId: string | undefined
    try {
      recordId = await this.createPresentationRow({
        solutionId: solution.id,
        uniqueName,
        title: input.title,
        devOpsId: input.devOpsId,
        kind: input.kind,
      })
    } catch (err) {
      console.warn('[solutions] working-solution row create failed:', err)
      throw new Error(
        `The solution "${uniqueName}" was created, but saving the working-solution ` +
          'record failed — it will appear under "Other" until the record exists.',
      )
    }
    return {
      ...solution,
      recordId,
      title: input.title,
      description: input.description,
      kind: input.kind,
      devOpsId: input.devOpsId,
      deploymentStatus: 'None',
    }
  }

  /** Create the ssid_workingsolution row for a solution. */
  private async createPresentationRow(
    input: TrackSolutionInput,
  ): Promise<string | undefined> {
    const workbenchSettingId = await this.defaultWorkbenchSettingId()
    const rowRecord = {
      ssid_name: input.title,
      ssid_devopsid: input.devOpsId,
      ssid_uniquesolutionname: input.uniqueName,
      ssid_solutionlink: makerSolutionUrl(null, input.solutionId),
      sst_type_opt: TYPE_OPT_BY_KIND[input.kind],
      ssid_deploymentstatus: DEPLOYMENT_STATUS_NONE,
      ...(workbenchSettingId
        ? {
            'ssid_WorkbenchSetting@odata.bind': `/ssid_workbenchsettings(${workbenchSettingId})`,
          }
        : {}),
    } as unknown as Omit<Ssid_workingsolutionsBase, 'ssid_workingsolutionid'>
    const rowResult = await Ssid_workingsolutionsService.create(rowRecord)
    if (!rowResult.success) {
      console.warn('[solutions] working-solution row create failed:', rowResult)
      throw new Error('Saving the working-solution record failed.')
    }
    return rowResult.data?.ssid_workingsolutionid
  }

  /** Change the Feature / Bug / Release classification of a record. */
  async updateSolutionType(
    recordId: string,
    kind: TrackSolutionInput['kind'],
  ): Promise<void> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.updateSolutionType(recordId, kind)
    const result = await Ssid_workingsolutionsService.update(
      recordId,
      {
        sst_type_opt: TYPE_OPT_BY_KIND[kind],
      } as unknown as Partial<
        Omit<Ssid_workingsolutionsBase, 'ssid_workingsolutionid'>
      >,
    )
    if (result && result.success === false) {
      console.warn('[solutions] type update failed:', result)
      throw new Error('Updating the type failed.')
    }
  }

  /** Point an orphaned record at an existing solution. */
  async linkSolution(
    recordId: string,
    target: { id: string; uniqueName: string },
  ): Promise<void> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.linkSolution(recordId, target)
    const result = await Ssid_workingsolutionsService.update(
      recordId,
      {
        ssid_uniquesolutionname: target.uniqueName,
        ssid_solutionlink: makerSolutionUrl(null, target.id),
      } as unknown as Partial<
        Omit<Ssid_workingsolutionsBase, 'ssid_workingsolutionid'>
      >,
    )
    if (result && result.success === false) {
      console.warn('[solutions] link update failed:', result)
      throw new Error('Linking the solution failed.')
    }
  }

  /** Attach a presentation record to an already existing solution. */
  async trackSolution(input: TrackSolutionInput): Promise<void> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockSolutionService.trackSolution(input)
    await this.createPresentationRow(input)
  }

  private currentUserPromise: Promise<{
    id: string | null
    name: string | null
  }> | null = null

  /**
   * Resolve the signed-in user's systemuser id once per session. The host
   * context only carries Entra-level identity (object id / UPN), so it is
   * matched against systemusers via the Dataverse connector.
   */
  async getCurrentUser(): Promise<{ id: string | null; name: string | null }> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockSolutionService.getCurrentUser()
    this.currentUserPromise ??= this.resolveCurrentUser()
    return this.currentUserPromise
  }

  private async resolveCurrentUser(): Promise<{
    id: string | null
    name: string | null
  }> {
    const fallbackName = hostUserHints.displayName ?? null

    // Primary: native data sources run as the signed-in user (unlike the
    // connector, which runs as its connection — here a service principal),
    // so Dataverse itself can answer "who am I" via the EqualUserId query
    // function.
    try {
      const result = await SystemusersService.getAll({
        select: ['systemuserid', 'fullname'],
        filter:
          "Microsoft.Dynamics.CRM.EqualUserId(PropertyName='systemuserid')",
        top: 1,
      })
      const row = result.data?.[0] as
        | { systemuserid?: string; fullname?: string }
        | undefined
      if (result.success && typeof row?.systemuserid === 'string') {
        return {
          id: row.systemuserid,
          name: row.fullname || fallbackName,
        }
      }
      console.warn('[solutions] EqualUserId lookup returned no row:', result)
    } catch (err) {
      console.warn('[solutions] EqualUserId lookup threw:', err)
    }

    // Fallback: match host-context identity hints against systemusers via
    // the connector (works regardless of the connection's own identity).
    try {
      let filter: string | null = null
      if (hostUserHints.entraObjectId) {
        filter = `azureactivedirectoryobjectid eq ${hostUserHints.entraObjectId}`
      } else if (hostUserHints.userPrincipalName) {
        const upn = hostUserHints.userPrincipalName.replace(/'/g, "''")
        filter = `domainname eq '${upn}'`
      }
      if (!filter) {
        console.info('[solutions] no user identity in host context:', hostUserHints)
        return { id: null, name: fallbackName }
      }
      const result = await MicrosoftDataverseService.ListRecords(
        'systemusers',
        undefined,
        undefined,
        undefined,
        'systemuserid,fullname',
        filter,
        undefined,
        undefined,
        undefined,
        1,
      )
      const row = (
        result.data as { value?: Record<string, unknown>[] } | undefined
      )?.value?.[0]
      if (row && typeof row.systemuserid === 'string') {
        return {
          id: row.systemuserid,
          name:
            typeof row.fullname === 'string' && row.fullname
              ? row.fullname
              : fallbackName,
        }
      }
      console.warn('[solutions] current user not found via', filter)
    } catch (err) {
      console.warn('[solutions] current user lookup failed:', err)
    }
    return { id: null, name: fallbackName }
  }

  /**
   * Final deletion after the UI's undo window: solution first (so a
   * failing solution delete leaves the tracking record intact), then the
   * presentation record. Deleting an unmanaged solution removes only the
   * container, not the components inside.
   */
  async deleteSolution(solution: WorkingSolution): Promise<void> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.deleteSolution(solution)
    if (!solution.solutionMissing && solution.id && !solution.id.startsWith('missing-')) {
      await SolutionsService.delete(solution.id)
    }
    if (solution.recordId) {
      await Ssid_workingsolutionsService.delete(solution.recordId)
    }
  }

  /** Raw `solutioncomponent` rows — root components plus their behaviors. */
  private async fetchRawComponents(
    solutionId: string,
  ): Promise<Solutioncomponents[] | null> {
    return fetchAll(
      (o) => SolutioncomponentsService.getAll(o),
      {
        select: [
          'solutioncomponentid',
          'componenttype',
          'objectid',
          'rootcomponentbehavior',
        ],
        filter: `_solutionid_value eq ${solutionId}`,
      },
    )
  }

  async listComponents(solutionId: string): Promise<SolutionComponentInfo[]> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.listComponents(solutionId)
    try {
      // The summary virtual table resolves display names (it's what the
      // maker portal renders); the raw table supplies rootcomponentbehavior,
      // which the merge needs. Join the two on objectid.
      const [summaryRows, rawRows] = await Promise.all([
        fetchAll(
          (o) => Msdyn_solutioncomponentsummariesService.getAll(o),
          {
            select: [
              'msdyn_solutioncomponentsummaryid',
              'msdyn_objectid',
              'msdyn_componenttype',
              'msdyn_componenttypename',
              'msdyn_displayname',
              'msdyn_name',
              'msdyn_schemaname',
              'msdyn_primaryentityname',
            ],
            filter: `msdyn_solutionid eq '${solutionId}'`,
          },
        ).catch((err) => {
          console.warn('[solutions] summary query threw:', err)
          return null
        }),
        this.fetchRawComponents(solutionId),
      ])

      const behaviorByObjectId = new Map<string, number>()
      for (const row of rawRows ?? []) {
        if (row.objectid && row.rootcomponentbehavior !== undefined)
          behaviorByObjectId.set(row.objectid, Number(row.rootcomponentbehavior))
      }

      const mapped = summaryRows?.length
        ? summaryRows.map((r) => summaryToComponentInfo(r, behaviorByObjectId))
        : (rawRows ?? []).map(toComponentInfo)
      if (!summaryRows?.length && !rawRows)
        return mockSolutionService.listComponents(solutionId)
      return mapped.sort(
        (a, b) =>
          a.typeName.localeCompare(b.typeName) ||
          a.displayName.localeCompare(b.displayName),
      )
    } catch (err) {
      console.warn('[solutions] listComponents() threw, falling back to mock:', err)
      return mockSolutionService.listComponents(solutionId)
    }
  }

  /**
   * Work item summary via the Azure DevOps connector. TEMPORARILY
   * DISABLED (DEVOPS_PANEL_ENABLED = false) while the service-principal
   * access to the DevOps org is being set up — the connector data source
   * has been removed from the app so users get no connection prompt.
   *
   * To restore (see TODO.md):
   *   pac code add-data-source -a shared_visualstudioteamservices
   *     -cr sst_CRDevOps -s <WorkbenchSchulz-id> -env <INT-11-url>
   * then re-import AzureDevOpsService and map ListWorkItems(ADO_ACCOUNT,
   * ADO_PROJECT_NAME, devOpsId): System_WorkItemType / System_Title /
   * System_State / System_AssignedTo → WorkItemInfo, with
   * devOpsWorkItemUrl(devOpsId) as the link.
   */
  async getWorkItem(devOpsId: string): Promise<WorkItemInfo | null> {
    const mode = await powerModeReady
    if (mode !== 'power-platform') return mockSolutionService.getWorkItem(devOpsId)
    if (!DEVOPS_PANEL_ENABLED) return null
    console.info('[devops] connector not wired — DEVOPS_PANEL_ENABLED without data source')
    return null
  }

  async mergeIntoDeployment(
    targetUniqueName: string,
    sourceSolutionIds: string[],
    onProgress?: (done: number, total: number) => void,
  ): Promise<MergeResult> {
    const mode = await powerModeReady
    if (mode !== 'power-platform')
      return mockSolutionService.mergeIntoDeployment(
        targetUniqueName,
        sourceSolutionIds,
        onProgress,
      )

    // Resolve target id + the components already present, so re-merges skip
    // instead of failing.
    const solutions = await this.listSolutions()
    const target = solutions.find((s) => s.uniqueName === targetUniqueName)
    if (!target) throw new Error(`Unknown target solution ${targetUniqueName}`)
    const existing = new Set(
      (await this.listComponents(target.id)).map((c) => c.objectId),
    )

    const queue: SolutionComponentInfo[] = []
    for (const id of sourceSolutionIds) {
      queue.push(...(await this.listComponents(id)))
    }

    const result: MergeResult = { added: 0, skipped: 0, errors: [] }
    let done = 0
    for (const component of queue) {
      if (existing.has(component.objectId)) {
        result.skipped++
      } else {
        try {
          // Carry the source's subcomponent behavior over to the target:
          // 0 = include subcomponents, 1 = do not include, 2 = shell only
          // (signalled by an empty IncludedComponentSettingsValues).
          const doNotIncludeSubcomponents =
            component.rootBehavior === 1 || component.rootBehavior === 2
          const res = await AddSolutionComponentService.AddSolutionComponent(
            component.objectId,
            component.typeCode,
            targetUniqueName,
            false,
            doNotIncludeSubcomponents,
            component.rootBehavior === 2 ? [] : undefined,
          )
          if (res.success) {
            existing.add(component.objectId)
            result.added++
          } else {
            console.warn('[solutions] AddSolutionComponent failed:', res)
            result.errors.push(
              `${component.typeName} ${shortGuid(component.objectId)}: rejected`,
            )
          }
        } catch (err) {
          result.errors.push(
            `${component.typeName} ${shortGuid(component.objectId)}: ${String(err)}`,
          )
        }
      }
      onProgress?.(++done, queue.length)
    }

    // Log the merge on the source rows' presentation records — the table
    // carries dedicated fields for exactly this.
    if (result.added > 0 || result.skipped > 0) {
      const mergedAt = new Date().toISOString()
      for (const source of solutions) {
        if (!sourceSolutionIds.includes(source.id) || !source.recordId) continue
        try {
          await Ssid_workingsolutionsService.update(
            source.recordId,
            {
              sst_mergeintodeploymentsolution: true,
              sst_lastmergeintodeploymentsolution: mergedAt,
              ssid_deploymentstatus: DEPLOYMENT_STATUS_MERGED,
            } as unknown as Partial<
              Omit<Ssid_workingsolutionsBase, 'ssid_workingsolutionid'>
            >,
          )
        } catch (err) {
          // Logging must not fail the merge itself.
          console.warn('[solutions] merge log update failed:', err)
        }
      }
    }
    return result
  }
}

export const dataverseSolutionService = new DataverseSolutionService()
